// The "departing from" vocabulary: every mainland-China prefecture city,
// every national capital, and the world's significant airport cities, each
// with its English and Chinese names (traditional only where it genuinely
// differs). Generated and cross-checked 2026-08-29. This is UI convenience
// vocabulary for the autocomplete: free text remains a valid departure
// value, so no real place is ever impossible to enter.
export const DEPARTURE_CITIES = [
  {"en": "Beijing", "zh": "北京", "country": "CHN"},
  {"en": "Tianjin", "zh": "天津", "country": "CHN"},
  {"en": "Shanghai", "zh": "上海", "country": "CHN"},
  {"en": "Chongqing", "zh": "重庆", "country": "CHN"},
  {"en": "Shijiazhuang", "zh": "石家庄", "country": "CHN"},
  {"en": "Tangshan", "zh": "唐山", "country": "CHN"},
  {"en": "Qinhuangdao", "zh": "秦皇岛", "country": "CHN"},
  {"en": "Handan", "zh": "邯郸", "country": "CHN"},
  {"en": "Xingtai", "zh": "邢台", "country": "CHN"},
  {"en": "Baoding", "zh": "保定", "country": "CHN"},
  {"en": "Zhangjiakou", "zh": "张家口", "country": "CHN"},
  {"en": "Chengde", "zh": "承德", "country": "CHN"},
  {"en": "Cangzhou", "zh": "沧州", "country": "CHN"},
  {"en": "Langfang", "zh": "廊坊", "country": "CHN"},
  {"en": "Hengshui", "zh": "衡水", "country": "CHN"},
  {"en": "Taiyuan", "zh": "太原", "country": "CHN"},
  {"en": "Datong", "zh": "大同", "country": "CHN"},
  {"en": "Yangquan", "zh": "阳泉", "country": "CHN"},
  {"en": "Changzhi", "zh": "长治", "country": "CHN"},
  {"en": "Jincheng", "zh": "晋城", "country": "CHN"},
  {"en": "Shuozhou", "zh": "朔州", "country": "CHN"},
  {"en": "Jinzhong", "zh": "晋中", "country": "CHN"},
  {"en": "Yuncheng", "zh": "运城", "country": "CHN"},
  {"en": "Xinzhou", "zh": "忻州", "country": "CHN"},
  {"en": "Linfen", "zh": "临汾", "country": "CHN"},
  {"en": "Lüliang", "zh": "吕梁", "country": "CHN"},
  {"en": "Hohhot", "zh": "呼和浩特", "country": "CHN"},
  {"en": "Baotou", "zh": "包头", "country": "CHN"},
  {"en": "Wuhai", "zh": "乌海", "country": "CHN"},
  {"en": "Chifeng", "zh": "赤峰", "country": "CHN"},
  {"en": "Tongliao", "zh": "通辽", "country": "CHN"},
  {"en": "Ordos", "zh": "鄂尔多斯", "country": "CHN"},
  {"en": "Hulunbuir", "zh": "呼伦贝尔", "country": "CHN"},
  {"en": "Bayannur", "zh": "巴彦淖尔", "country": "CHN"},
  {"en": "Ulanqab", "zh": "乌兰察布", "country": "CHN"},
  {"en": "Hinggan League", "zh": "兴安盟", "country": "CHN"},
  {"en": "Xilingol League", "zh": "锡林郭勒盟", "country": "CHN"},
  {"en": "Alxa League", "zh": "阿拉善盟", "country": "CHN"},
  {"en": "Shenyang", "zh": "沈阳", "country": "CHN"},
  {"en": "Dalian", "zh": "大连", "country": "CHN"},
  {"en": "Anshan", "zh": "鞍山", "country": "CHN"},
  {"en": "Fushun", "zh": "抚顺", "country": "CHN"},
  {"en": "Benxi", "zh": "本溪", "country": "CHN"},
  {"en": "Dandong", "zh": "丹东", "country": "CHN"},
  {"en": "Jinzhou", "zh": "锦州", "country": "CHN"},
  {"en": "Yingkou", "zh": "营口", "country": "CHN"},
  {"en": "Fuxin", "zh": "阜新", "country": "CHN"},
  {"en": "Liaoyang", "zh": "辽阳", "country": "CHN"},
  {"en": "Panjin", "zh": "盘锦", "country": "CHN"},
  {"en": "Tieling", "zh": "铁岭", "country": "CHN"},
  {"en": "Chaoyang", "zh": "朝阳", "country": "CHN"},
  {"en": "Huludao", "zh": "葫芦岛", "country": "CHN"},
  {"en": "Changchun", "zh": "长春", "country": "CHN"},
  {"en": "Jilin", "zh": "吉林", "country": "CHN"},
  {"en": "Siping", "zh": "四平", "country": "CHN"},
  {"en": "Liaoyuan", "zh": "辽源", "country": "CHN"},
  {"en": "Tonghua", "zh": "通化", "country": "CHN"},
  {"en": "Baishan", "zh": "白山", "country": "CHN"},
  {"en": "Songyuan", "zh": "松原", "country": "CHN"},
  {"en": "Baicheng", "zh": "白城", "country": "CHN"},
  {"en": "Yanbian", "zh": "延边", "country": "CHN"},
  {"en": "Harbin", "zh": "哈尔滨", "country": "CHN"},
  {"en": "Qiqihar", "zh": "齐齐哈尔", "country": "CHN"},
  {"en": "Jixi", "zh": "鸡西", "country": "CHN"},
  {"en": "Hegang", "zh": "鹤岗", "country": "CHN"},
  {"en": "Shuangyashan", "zh": "双鸭山", "country": "CHN"},
  {"en": "Daqing", "zh": "大庆", "country": "CHN"},
  {"en": "Yichun", "zh": "伊春", "country": "CHN"},
  {"en": "Jiamusi", "zh": "佳木斯", "country": "CHN"},
  {"en": "Qitaihe", "zh": "七台河", "country": "CHN"},
  {"en": "Mudanjiang", "zh": "牡丹江", "country": "CHN"},
  {"en": "Heihe", "zh": "黑河", "country": "CHN"},
  {"en": "Suihua", "zh": "绥化", "country": "CHN"},
  {"en": "Daxing'anling", "zh": "大兴安岭", "country": "CHN"},
  {"en": "Nanjing", "zh": "南京", "country": "CHN"},
  {"en": "Wuxi", "zh": "无锡", "country": "CHN"},
  {"en": "Xuzhou", "zh": "徐州", "country": "CHN"},
  {"en": "Changzhou", "zh": "常州", "country": "CHN"},
  {"en": "Suzhou", "zh": "苏州", "country": "CHN"},
  {"en": "Nantong", "zh": "南通", "country": "CHN"},
  {"en": "Lianyungang", "zh": "连云港", "country": "CHN"},
  {"en": "Huai'an", "zh": "淮安", "country": "CHN"},
  {"en": "Yancheng", "zh": "盐城", "country": "CHN"},
  {"en": "Yangzhou", "zh": "扬州", "country": "CHN"},
  {"en": "Zhenjiang", "zh": "镇江", "country": "CHN"},
  {"en": "Taizhou", "zh": "泰州", "country": "CHN"},
  {"en": "Suqian", "zh": "宿迁", "country": "CHN"},
  {"en": "Hangzhou", "zh": "杭州", "country": "CHN"},
  {"en": "Ningbo", "zh": "宁波", "country": "CHN"},
  {"en": "Wenzhou", "zh": "温州", "country": "CHN"},
  {"en": "Jiaxing", "zh": "嘉兴", "country": "CHN"},
  {"en": "Huzhou", "zh": "湖州", "country": "CHN"},
  {"en": "Shaoxing", "zh": "绍兴", "country": "CHN"},
  {"en": "Jinhua", "zh": "金华", "country": "CHN"},
  {"en": "Quzhou", "zh": "衢州", "country": "CHN"},
  {"en": "Zhoushan", "zh": "舟山", "country": "CHN"},
  {"en": "Lishui", "zh": "丽水", "country": "CHN"},
  {"en": "Hefei", "zh": "合肥", "country": "CHN"},
  {"en": "Wuhu", "zh": "芜湖", "country": "CHN"},
  {"en": "Bengbu", "zh": "蚌埠", "country": "CHN"},
  {"en": "Huainan", "zh": "淮南", "country": "CHN"},
  {"en": "Ma'anshan", "zh": "马鞍山", "country": "CHN"},
  {"en": "Huaibei", "zh": "淮北", "country": "CHN"},
  {"en": "Tongling", "zh": "铜陵", "country": "CHN"},
  {"en": "Anqing", "zh": "安庆", "country": "CHN"},
  {"en": "Huangshan", "zh": "黄山", "country": "CHN"},
  {"en": "Chuzhou", "zh": "滁州", "country": "CHN"},
  {"en": "Fuyang", "zh": "阜阳", "country": "CHN"},
  {"en": "Lu'an", "zh": "六安", "country": "CHN"},
  {"en": "Bozhou", "zh": "亳州", "country": "CHN"},
  {"en": "Chizhou", "zh": "池州", "country": "CHN"},
  {"en": "Xuancheng", "zh": "宣城", "country": "CHN"},
  {"en": "Fuzhou", "zh": "福州", "country": "CHN"},
  {"en": "Xiamen", "zh": "厦门", "country": "CHN"},
  {"en": "Putian", "zh": "莆田", "country": "CHN"},
  {"en": "Sanming", "zh": "三明", "country": "CHN"},
  {"en": "Quanzhou", "zh": "泉州", "country": "CHN"},
  {"en": "Zhangzhou", "zh": "漳州", "country": "CHN"},
  {"en": "Nanping", "zh": "南平", "country": "CHN"},
  {"en": "Longyan", "zh": "龙岩", "country": "CHN"},
  {"en": "Ningde", "zh": "宁德", "country": "CHN"},
  {"en": "Nanchang", "zh": "南昌", "country": "CHN"},
  {"en": "Jingdezhen", "zh": "景德镇", "country": "CHN"},
  {"en": "Pingxiang", "zh": "萍乡", "country": "CHN"},
  {"en": "Jiujiang", "zh": "九江", "country": "CHN"},
  {"en": "Xinyu", "zh": "新余", "country": "CHN"},
  {"en": "Yingtan", "zh": "鹰潭", "country": "CHN"},
  {"en": "Ganzhou", "zh": "赣州", "country": "CHN"},
  {"en": "Ji'an", "zh": "吉安", "country": "CHN"},
  {"en": "Shangrao", "zh": "上饶", "country": "CHN"},
  {"en": "Jinan", "zh": "济南", "country": "CHN"},
  {"en": "Qingdao", "zh": "青岛", "country": "CHN"},
  {"en": "Zibo", "zh": "淄博", "country": "CHN"},
  {"en": "Zaozhuang", "zh": "枣庄", "country": "CHN"},
  {"en": "Dongying", "zh": "东营", "country": "CHN"},
  {"en": "Yantai", "zh": "烟台", "country": "CHN"},
  {"en": "Weifang", "zh": "潍坊", "country": "CHN"},
  {"en": "Jining", "zh": "济宁", "country": "CHN"},
  {"en": "Tai'an", "zh": "泰安", "country": "CHN"},
  {"en": "Weihai", "zh": "威海", "country": "CHN"},
  {"en": "Rizhao", "zh": "日照", "country": "CHN"},
  {"en": "Linyi", "zh": "临沂", "country": "CHN"},
  {"en": "Dezhou", "zh": "德州", "country": "CHN"},
  {"en": "Liaocheng", "zh": "聊城", "country": "CHN"},
  {"en": "Binzhou", "zh": "滨州", "country": "CHN"},
  {"en": "Heze", "zh": "菏泽", "country": "CHN"},
  {"en": "Zhengzhou", "zh": "郑州", "country": "CHN"},
  {"en": "Kaifeng", "zh": "开封", "country": "CHN"},
  {"en": "Luoyang", "zh": "洛阳", "country": "CHN"},
  {"en": "Pingdingshan", "zh": "平顶山", "country": "CHN"},
  {"en": "Anyang", "zh": "安阳", "country": "CHN"},
  {"en": "Hebi", "zh": "鹤壁", "country": "CHN"},
  {"en": "Xinxiang", "zh": "新乡", "country": "CHN"},
  {"en": "Jiaozuo", "zh": "焦作", "country": "CHN"},
  {"en": "Puyang", "zh": "濮阳", "country": "CHN"},
  {"en": "Xuchang", "zh": "许昌", "country": "CHN"},
  {"en": "Luohe", "zh": "漯河", "country": "CHN"},
  {"en": "Sanmenxia", "zh": "三门峡", "country": "CHN"},
  {"en": "Nanyang", "zh": "南阳", "country": "CHN"},
  {"en": "Shangqiu", "zh": "商丘", "country": "CHN"},
  {"en": "Xinyang", "zh": "信阳", "country": "CHN"},
  {"en": "Zhoukou", "zh": "周口", "country": "CHN"},
  {"en": "Zhumadian", "zh": "驻马店", "country": "CHN"},
  {"en": "Wuhan", "zh": "武汉", "country": "CHN"},
  {"en": "Huangshi", "zh": "黄石", "country": "CHN"},
  {"en": "Shiyan", "zh": "十堰", "country": "CHN"},
  {"en": "Yichang", "zh": "宜昌", "country": "CHN"},
  {"en": "Xiangyang", "zh": "襄阳", "country": "CHN"},
  {"en": "Ezhou", "zh": "鄂州", "country": "CHN"},
  {"en": "Jingmen", "zh": "荆门", "country": "CHN"},
  {"en": "Xiaogan", "zh": "孝感", "country": "CHN"},
  {"en": "Jingzhou", "zh": "荆州", "country": "CHN"},
  {"en": "Huanggang", "zh": "黄冈", "country": "CHN"},
  {"en": "Xianning", "zh": "咸宁", "country": "CHN"},
  {"en": "Suizhou", "zh": "随州", "country": "CHN"},
  {"en": "Enshi", "zh": "恩施", "country": "CHN"},
  {"en": "Changsha", "zh": "长沙", "country": "CHN"},
  {"en": "Zhuzhou", "zh": "株洲", "country": "CHN"},
  {"en": "Xiangtan", "zh": "湘潭", "country": "CHN"},
  {"en": "Hengyang", "zh": "衡阳", "country": "CHN"},
  {"en": "Shaoyang", "zh": "邵阳", "country": "CHN"},
  {"en": "Yueyang", "zh": "岳阳", "country": "CHN"},
  {"en": "Changde", "zh": "常德", "country": "CHN"},
  {"en": "Zhangjiajie", "zh": "张家界", "country": "CHN"},
  {"en": "Yiyang", "zh": "益阳", "country": "CHN"},
  {"en": "Chenzhou", "zh": "郴州", "country": "CHN"},
  {"en": "Yongzhou", "zh": "永州", "country": "CHN"},
  {"en": "Huaihua", "zh": "怀化", "country": "CHN"},
  {"en": "Loudi", "zh": "娄底", "country": "CHN"},
  {"en": "Xiangxi", "zh": "湘西", "country": "CHN"},
  {"en": "Guangzhou", "zh": "广州", "country": "CHN"},
  {"en": "Shaoguan", "zh": "韶关", "country": "CHN"},
  {"en": "Shenzhen", "zh": "深圳", "country": "CHN"},
  {"en": "Zhuhai", "zh": "珠海", "country": "CHN"},
  {"en": "Shantou", "zh": "汕头", "country": "CHN"},
  {"en": "Foshan", "zh": "佛山", "country": "CHN"},
  {"en": "Jiangmen", "zh": "江门", "country": "CHN"},
  {"en": "Zhanjiang", "zh": "湛江", "country": "CHN"},
  {"en": "Maoming", "zh": "茂名", "country": "CHN"},
  {"en": "Zhaoqing", "zh": "肇庆", "country": "CHN"},
  {"en": "Huizhou", "zh": "惠州", "country": "CHN"},
  {"en": "Meizhou", "zh": "梅州", "country": "CHN"},
  {"en": "Shanwei", "zh": "汕尾", "country": "CHN"},
  {"en": "Heyuan", "zh": "河源", "country": "CHN"},
  {"en": "Yangjiang", "zh": "阳江", "country": "CHN"},
  {"en": "Qingyuan", "zh": "清远", "country": "CHN"},
  {"en": "Dongguan", "zh": "东莞", "country": "CHN"},
  {"en": "Zhongshan", "zh": "中山", "country": "CHN"},
  {"en": "Chaozhou", "zh": "潮州", "country": "CHN"},
  {"en": "Jieyang", "zh": "揭阳", "country": "CHN"},
  {"en": "Yunfu", "zh": "云浮", "country": "CHN"},
  {"en": "Nanning", "zh": "南宁", "country": "CHN"},
  {"en": "Liuzhou", "zh": "柳州", "country": "CHN"},
  {"en": "Guilin", "zh": "桂林", "country": "CHN"},
  {"en": "Wuzhou", "zh": "梧州", "country": "CHN"},
  {"en": "Beihai", "zh": "北海", "country": "CHN"},
  {"en": "Fangchenggang", "zh": "防城港", "country": "CHN"},
  {"en": "Qinzhou", "zh": "钦州", "country": "CHN"},
  {"en": "Guigang", "zh": "贵港", "country": "CHN"},
  {"en": "Yulin", "zh": "玉林", "country": "CHN"},
  {"en": "Baise", "zh": "百色", "country": "CHN"},
  {"en": "Hezhou", "zh": "贺州", "country": "CHN"},
  {"en": "Hechi", "zh": "河池", "country": "CHN"},
  {"en": "Laibin", "zh": "来宾", "country": "CHN"},
  {"en": "Chongzuo", "zh": "崇左", "country": "CHN"},
  {"en": "Haikou", "zh": "海口", "country": "CHN"},
  {"en": "Sanya", "zh": "三亚", "country": "CHN"},
  {"en": "Sansha", "zh": "三沙", "country": "CHN"},
  {"en": "Danzhou", "zh": "儋州", "country": "CHN"},
  {"en": "Chengdu", "zh": "成都", "country": "CHN"},
  {"en": "Zigong", "zh": "自贡", "country": "CHN"},
  {"en": "Panzhihua", "zh": "攀枝花", "country": "CHN"},
  {"en": "Luzhou", "zh": "泸州", "country": "CHN"},
  {"en": "Deyang", "zh": "德阳", "country": "CHN"},
  {"en": "Mianyang", "zh": "绵阳", "country": "CHN"},
  {"en": "Guangyuan", "zh": "广元", "country": "CHN"},
  {"en": "Suining", "zh": "遂宁", "country": "CHN"},
  {"en": "Neijiang", "zh": "内江", "country": "CHN"},
  {"en": "Leshan", "zh": "乐山", "country": "CHN"},
  {"en": "Nanchong", "zh": "南充", "country": "CHN"},
  {"en": "Meishan", "zh": "眉山", "country": "CHN"},
  {"en": "Yibin", "zh": "宜宾", "country": "CHN"},
  {"en": "Guang'an", "zh": "广安", "country": "CHN"},
  {"en": "Dazhou", "zh": "达州", "country": "CHN"},
  {"en": "Ya'an", "zh": "雅安", "country": "CHN"},
  {"en": "Bazhong", "zh": "巴中", "country": "CHN"},
  {"en": "Ziyang", "zh": "资阳", "country": "CHN"},
  {"en": "Aba", "zh": "阿坝", "country": "CHN"},
  {"en": "Garze", "zh": "甘孜", "country": "CHN"},
  {"en": "Liangshan", "zh": "凉山", "country": "CHN"},
  {"en": "Guiyang", "zh": "贵阳", "country": "CHN"},
  {"en": "Liupanshui", "zh": "六盘水", "country": "CHN"},
  {"en": "Zunyi", "zh": "遵义", "country": "CHN"},
  {"en": "Anshun", "zh": "安顺", "country": "CHN"},
  {"en": "Bijie", "zh": "毕节", "country": "CHN"},
  {"en": "Tongren", "zh": "铜仁", "country": "CHN"},
  {"en": "Qianxinan", "zh": "黔西南", "country": "CHN"},
  {"en": "Qiandongnan", "zh": "黔东南", "country": "CHN"},
  {"en": "Qiannan", "zh": "黔南", "country": "CHN"},
  {"en": "Kunming", "zh": "昆明", "country": "CHN"},
  {"en": "Qujing", "zh": "曲靖", "country": "CHN"},
  {"en": "Yuxi", "zh": "玉溪", "country": "CHN"},
  {"en": "Baoshan", "zh": "保山", "country": "CHN"},
  {"en": "Zhaotong", "zh": "昭通", "country": "CHN"},
  {"en": "Lijiang", "zh": "丽江", "country": "CHN"},
  {"en": "Pu'er", "zh": "普洱", "country": "CHN"},
  {"en": "Lincang", "zh": "临沧", "country": "CHN"},
  {"en": "Chuxiong", "zh": "楚雄", "country": "CHN"},
  {"en": "Honghe", "zh": "红河", "country": "CHN"},
  {"en": "Wenshan", "zh": "文山", "country": "CHN"},
  {"en": "Xishuangbanna", "zh": "西双版纳", "country": "CHN"},
  {"en": "Dali", "zh": "大理", "country": "CHN"},
  {"en": "Dehong", "zh": "德宏", "country": "CHN"},
  {"en": "Nujiang", "zh": "怒江", "country": "CHN"},
  {"en": "Diqing", "zh": "迪庆", "country": "CHN"},
  {"en": "Lhasa", "zh": "拉萨", "country": "CHN"},
  {"en": "Shigatse", "zh": "日喀则", "country": "CHN"},
  {"en": "Chamdo", "zh": "昌都", "country": "CHN"},
  {"en": "Nyingchi", "zh": "林芝", "country": "CHN"},
  {"en": "Shannan", "zh": "山南", "country": "CHN"},
  {"en": "Nagqu", "zh": "那曲", "country": "CHN"},
  {"en": "Ngari", "zh": "阿里", "country": "CHN"},
  {"en": "Xi'an", "zh": "西安", "country": "CHN"},
  {"en": "Tongchuan", "zh": "铜川", "country": "CHN"},
  {"en": "Baoji", "zh": "宝鸡", "country": "CHN"},
  {"en": "Xianyang", "zh": "咸阳", "country": "CHN"},
  {"en": "Weinan", "zh": "渭南", "country": "CHN"},
  {"en": "Yan'an", "zh": "延安", "country": "CHN"},
  {"en": "Hanzhong", "zh": "汉中", "country": "CHN"},
  {"en": "Ankang", "zh": "安康", "country": "CHN"},
  {"en": "Shangluo", "zh": "商洛", "country": "CHN"},
  {"en": "Lanzhou", "zh": "兰州", "country": "CHN"},
  {"en": "Jiayuguan", "zh": "嘉峪关", "country": "CHN"},
  {"en": "Jinchang", "zh": "金昌", "country": "CHN"},
  {"en": "Baiyin", "zh": "白银", "country": "CHN"},
  {"en": "Tianshui", "zh": "天水", "country": "CHN"},
  {"en": "Wuwei", "zh": "武威", "country": "CHN"},
  {"en": "Zhangye", "zh": "张掖", "country": "CHN"},
  {"en": "Pingliang", "zh": "平凉", "country": "CHN"},
  {"en": "Jiuquan", "zh": "酒泉", "country": "CHN"},
  {"en": "Qingyang", "zh": "庆阳", "country": "CHN"},
  {"en": "Dingxi", "zh": "定西", "country": "CHN"},
  {"en": "Longnan", "zh": "陇南", "country": "CHN"},
  {"en": "Linxia", "zh": "临夏", "country": "CHN"},
  {"en": "Gannan", "zh": "甘南", "country": "CHN"},
  {"en": "Xining", "zh": "西宁", "country": "CHN"},
  {"en": "Haidong", "zh": "海东", "country": "CHN"},
  {"en": "Haibei", "zh": "海北", "country": "CHN"},
  {"en": "Huangnan", "zh": "黄南", "country": "CHN"},
  {"en": "Hainan", "zh": "海南", "country": "CHN"},
  {"en": "Golog", "zh": "果洛", "country": "CHN"},
  {"en": "Yushu", "zh": "玉树", "country": "CHN"},
  {"en": "Haixi", "zh": "海西", "country": "CHN"},
  {"en": "Yinchuan", "zh": "银川", "country": "CHN"},
  {"en": "Shizuishan", "zh": "石嘴山", "country": "CHN"},
  {"en": "Wuzhong", "zh": "吴忠", "country": "CHN"},
  {"en": "Guyuan", "zh": "固原", "country": "CHN"},
  {"en": "Zhongwei", "zh": "中卫", "country": "CHN"},
  {"en": "Urumqi", "zh": "乌鲁木齐", "country": "CHN"},
  {"en": "Karamay", "zh": "克拉玛依", "country": "CHN"},
  {"en": "Turpan", "zh": "吐鲁番", "country": "CHN"},
  {"en": "Hami", "zh": "哈密", "country": "CHN"},
  {"en": "Changji", "zh": "昌吉", "country": "CHN"},
  {"en": "Bortala", "zh": "博尔塔拉", "country": "CHN"},
  {"en": "Bayingolin", "zh": "巴音郭楞", "country": "CHN"},
  {"en": "Aksu", "zh": "阿克苏", "country": "CHN"},
  {"en": "Kizilsu", "zh": "克孜勒苏", "country": "CHN"},
  {"en": "Kashgar", "zh": "喀什", "country": "CHN"},
  {"en": "Hotan", "zh": "和田", "country": "CHN"},
  {"en": "Ili", "zh": "伊犁", "country": "CHN"},
  {"en": "Tacheng", "zh": "塔城", "country": "CHN"},
  {"en": "Altay", "zh": "阿勒泰", "country": "CHN"},
  {"en": "Hong Kong", "zh": "香港", "hant": "香港", "country": "HKG"},
  {"en": "Macau", "zh": "澳门", "hant": "澳門", "country": "MAC"},
  {"en": "Taipei", "zh": "台北", "hant": "台北", "country": "TWN"},
  {"en": "Kaohsiung", "zh": "高雄", "hant": "高雄", "country": "TWN"},
  {"en": "Taichung", "zh": "台中", "hant": "台中", "country": "TWN"},
  {"en": "Tainan", "zh": "台南", "hant": "台南", "country": "TWN"},
  {"en": "Hsinchu", "zh": "新竹", "hant": "新竹", "country": "TWN"},
  {"en": "Tokyo", "zh": "东京", "country": "JPN"},
  {"en": "Osaka", "zh": "大阪", "country": "JPN"},
  {"en": "Nagoya", "zh": "名古屋", "country": "JPN"},
  {"en": "Fukuoka", "zh": "福冈", "country": "JPN"},
  {"en": "Sapporo", "zh": "札幌", "country": "JPN"},
  {"en": "Naha", "zh": "那霸", "country": "JPN"},
  {"en": "Sendai", "zh": "仙台", "country": "JPN"},
  {"en": "Hiroshima", "zh": "广岛", "country": "JPN"},
  {"en": "Okayama", "zh": "冈山", "country": "JPN"},
  {"en": "Takamatsu", "zh": "高松", "country": "JPN"},
  {"en": "Matsuyama", "zh": "松山", "country": "JPN"},
  {"en": "Kumamoto", "zh": "熊本", "country": "JPN"},
  {"en": "Kagoshima", "zh": "鹿儿岛", "country": "JPN"},
  {"en": "Nagasaki", "zh": "长崎", "country": "JPN"},
  {"en": "Miyazaki", "zh": "宫崎", "country": "JPN"},
  {"en": "Oita", "zh": "大分", "country": "JPN"},
  {"en": "Kitakyushu", "zh": "北九州", "country": "JPN"},
  {"en": "Niigata", "zh": "新潟", "country": "JPN"},
  {"en": "Shizuoka", "zh": "静冈", "country": "JPN"},
  {"en": "Asahikawa", "zh": "旭川", "country": "JPN"},
  {"en": "Hakodate", "zh": "函馆", "country": "JPN"},
  {"en": "Seoul", "zh": "首尔", "country": "KOR"},
  {"en": "Busan", "zh": "釜山", "country": "KOR"},
  {"en": "Jeju", "zh": "济州", "country": "KOR"},
  {"en": "Daegu", "zh": "大邱", "country": "KOR"},
  {"en": "Cheongju", "zh": "清州", "country": "KOR"},
  {"en": "Muan", "zh": "务安", "country": "KOR"},
  {"en": "Yangyang", "zh": "襄阳", "country": "KOR"},
  {"en": "Ulaanbaatar", "zh": "乌兰巴托", "country": "MNG"},
  {"en": "Pyongyang", "zh": "平壤", "country": "PRK"},
  {"en": "Bangkok", "zh": "曼谷", "country": "THA"},
  {"en": "Chiang Mai", "zh": "清迈", "country": "THA"},
  {"en": "Phuket", "zh": "普吉岛", "country": "THA"},
  {"en": "Krabi", "zh": "甲米", "hant": "喀比", "country": "THA"},
  {"en": "Koh Samui", "zh": "苏梅岛", "hant": "蘇美島", "country": "THA"},
  {"en": "Pattaya", "zh": "芭提雅", "hant": "芭達雅", "country": "THA"},
  {"en": "Hat Yai", "zh": "合艾", "country": "THA"},
  {"en": "Chiang Rai", "zh": "清莱", "country": "THA"},
  {"en": "Hanoi", "zh": "河内", "country": "VNM"},
  {"en": "Ho Chi Minh City", "zh": "胡志明市", "country": "VNM"},
  {"en": "Da Nang", "zh": "岘港", "country": "VNM"},
  {"en": "Nha Trang", "zh": "芽庄", "country": "VNM"},
  {"en": "Phu Quoc", "zh": "富国岛", "country": "VNM"},
  {"en": "Hai Phong", "zh": "海防", "country": "VNM"},
  {"en": "Hue", "zh": "顺化", "country": "VNM"},
  {"en": "Da Lat", "zh": "大叻", "country": "VNM"},
  {"en": "Can Tho", "zh": "芹苴", "country": "VNM"},
  {"en": "Kuala Lumpur", "zh": "吉隆坡", "country": "MYS"},
  {"en": "Penang", "zh": "槟城", "country": "MYS"},
  {"en": "Kota Kinabalu", "zh": "亚庇", "country": "MYS"},
  {"en": "Kuching", "zh": "古晋", "country": "MYS"},
  {"en": "Johor Bahru", "zh": "新山", "country": "MYS"},
  {"en": "Langkawi", "zh": "兰卡威", "country": "MYS"},
  {"en": "Ipoh", "zh": "怡保", "country": "MYS"},
  {"en": "Miri", "zh": "美里", "country": "MYS"},
  {"en": "Kota Bharu", "zh": "哥打巴鲁", "country": "MYS"},
  {"en": "Singapore", "zh": "新加坡", "country": "SGP"},
  {"en": "Jakarta", "zh": "雅加达", "country": "IDN"},
  {"en": "Bali", "zh": "巴厘岛", "hant": "峇里島", "country": "IDN"},
  {"en": "Surabaya", "zh": "泗水", "country": "IDN"},
  {"en": "Medan", "zh": "棉兰", "country": "IDN"},
  {"en": "Bandung", "zh": "万隆", "country": "IDN"},
  {"en": "Yogyakarta", "zh": "日惹", "country": "IDN"},
  {"en": "Semarang", "zh": "三宝垄", "country": "IDN"},
  {"en": "Makassar", "zh": "望加锡", "country": "IDN"},
  {"en": "Balikpapan", "zh": "巴厘巴板", "hant": "峇里巴板", "country": "IDN"},
  {"en": "Manado", "zh": "万鸦老", "country": "IDN"},
  {"en": "Batam", "zh": "巴淡", "country": "IDN"},
  {"en": "Pekanbaru", "zh": "北干巴鲁", "country": "IDN"},
  {"en": "Lombok", "zh": "龙目岛", "country": "IDN"},
  {"en": "Manila", "zh": "马尼拉", "country": "PHL"},
  {"en": "Cebu", "zh": "宿务", "hant": "宿霧", "country": "PHL"},
  {"en": "Davao", "zh": "达沃", "country": "PHL"},
  {"en": "Iloilo", "zh": "伊洛伊洛", "country": "PHL"},
  {"en": "Kalibo", "zh": "卡利博", "country": "PHL"},
  {"en": "Puerto Princesa", "zh": "公主港", "country": "PHL"},
  {"en": "Clark", "zh": "克拉克", "country": "PHL"},
  {"en": "Phnom Penh", "zh": "金边", "country": "KHM"},
  {"en": "Siem Reap", "zh": "暹粒", "country": "KHM"},
  {"en": "Sihanoukville", "zh": "西哈努克市", "hant": "施亞努市", "country": "KHM"},
  {"en": "Vientiane", "zh": "万象", "hant": "永珍", "country": "LAO"},
  {"en": "Luang Prabang", "zh": "琅勃拉邦", "hant": "龍坡邦", "country": "LAO"},
  {"en": "Yangon", "zh": "仰光", "country": "MMR"},
  {"en": "Mandalay", "zh": "曼德勒", "country": "MMR"},
  {"en": "Naypyidaw", "zh": "内比都", "country": "MMR"},
  {"en": "Bandar Seri Begawan", "zh": "斯里巴加湾市", "hant": "斯里巴卡旺市", "country": "BRN"},
  {"en": "Dili", "zh": "帝力", "country": "TLS"},
  {"en": "New Delhi", "zh": "新德里", "country": "IND"},
  {"en": "Mumbai", "zh": "孟买", "country": "IND"},
  {"en": "Bengaluru", "zh": "班加罗尔", "country": "IND"},
  {"en": "Chennai", "zh": "金奈", "hant": "清奈", "country": "IND"},
  {"en": "Hyderabad", "zh": "海得拉巴", "hant": "海德拉巴", "country": "IND"},
  {"en": "Kolkata", "zh": "加尔各答", "country": "IND"},
  {"en": "Ahmedabad", "zh": "艾哈迈达巴德", "country": "IND"},
  {"en": "Pune", "zh": "浦那", "country": "IND"},
  {"en": "Kochi", "zh": "科钦", "country": "IND"},
  {"en": "Goa", "zh": "果阿", "country": "IND"},
  {"en": "Jaipur", "zh": "斋浦尔", "country": "IND"},
  {"en": "Lucknow", "zh": "勒克瑙", "country": "IND"},
  {"en": "Amritsar", "zh": "阿姆利则", "country": "IND"},
  {"en": "Thiruvananthapuram", "zh": "特里凡得琅", "country": "IND"},
  {"en": "Kozhikode", "zh": "科泽科德", "country": "IND"},
  {"en": "Varanasi", "zh": "瓦拉纳西", "country": "IND"},
  {"en": "Islamabad", "zh": "伊斯兰堡", "hant": "伊斯蘭馬巴德", "country": "PAK"},
  {"en": "Karachi", "zh": "卡拉奇", "hant": "喀拉蚩", "country": "PAK"},
  {"en": "Lahore", "zh": "拉合尔", "country": "PAK"},
  {"en": "Peshawar", "zh": "白沙瓦", "country": "PAK"},
  {"en": "Multan", "zh": "木尔坦", "country": "PAK"},
  {"en": "Sialkot", "zh": "锡亚尔科特", "country": "PAK"},
  {"en": "Dhaka", "zh": "达卡", "country": "BGD"},
  {"en": "Chittagong", "zh": "吉大港", "country": "BGD"},
  {"en": "Sylhet", "zh": "锡尔赫特", "country": "BGD"},
  {"en": "Colombo", "zh": "科伦坡", "hant": "可倫坡", "country": "LKA"},
  {"en": "Kathmandu", "zh": "加德满都", "country": "NPL"},
  {"en": "Pokhara", "zh": "博卡拉", "country": "NPL"},
  {"en": "Thimphu", "zh": "廷布", "country": "BTN"},
  {"en": "Malé", "zh": "马累", "country": "MDV"},
  {"en": "Kabul", "zh": "喀布尔", "country": "AFG"},
  {"en": "Almaty", "zh": "阿拉木图", "country": "KAZ"},
  {"en": "Astana", "zh": "阿斯塔纳", "country": "KAZ"},
  {"en": "Shymkent", "zh": "奇姆肯特", "country": "KAZ"},
  {"en": "Tashkent", "zh": "塔什干", "country": "UZB"},
  {"en": "Samarkand", "zh": "撒马尔罕", "country": "UZB"},
  {"en": "Bishkek", "zh": "比什凯克", "country": "KGZ"},
  {"en": "Dushanbe", "zh": "杜尚别", "country": "TJK"},
  {"en": "Ashgabat", "zh": "阿什哈巴德", "country": "TKM"},
  {"en": "Baku", "zh": "巴库", "country": "AZE"},
  {"en": "Tbilisi", "zh": "第比利斯", "hant": "提比里斯", "country": "GEO"},
  {"en": "Yerevan", "zh": "埃里温", "hant": "葉里溫", "country": "ARM"},
  {"en": "Dubai", "zh": "迪拜", "hant": "杜拜", "country": "ARE"},
  {"en": "Abu Dhabi", "zh": "阿布扎比", "hant": "阿布達比", "country": "ARE"},
  {"en": "Sharjah", "zh": "沙迦", "country": "ARE"},
  {"en": "Doha", "zh": "多哈", "hant": "杜哈", "country": "QAT"},
  {"en": "Riyadh", "zh": "利雅得", "hant": "利雅德", "country": "SAU"},
  {"en": "Jeddah", "zh": "吉达", "country": "SAU"},
  {"en": "Dammam", "zh": "达曼", "country": "SAU"},
  {"en": "Medina", "zh": "麦地那", "country": "SAU"},
  {"en": "Kuwait City", "zh": "科威特城", "hant": "科威特市", "country": "KWT"},
  {"en": "Manama", "zh": "麦纳麦", "hant": "麥納瑪", "country": "BHR"},
  {"en": "Muscat", "zh": "马斯喀特", "country": "OMN"},
  {"en": "Salalah", "zh": "塞拉莱", "country": "OMN"},
  {"en": "Sanaa", "zh": "萨那", "hant": "沙那", "country": "YEM"},
  {"en": "Baghdad", "zh": "巴格达", "country": "IRQ"},
  {"en": "Erbil", "zh": "埃尔比勒", "country": "IRQ"},
  {"en": "Basra", "zh": "巴士拉", "country": "IRQ"},
  {"en": "Damascus", "zh": "大马士革", "country": "SYR"},
  {"en": "Beirut", "zh": "贝鲁特", "country": "LBN"},
  {"en": "Amman", "zh": "安曼", "country": "JOR"},
  {"en": "Tel Aviv", "zh": "特拉维夫", "country": "ISR"},
  {"en": "Jerusalem", "zh": "耶路撒冷", "country": "ISR"},
  {"en": "Istanbul", "zh": "伊斯坦布尔", "hant": "伊斯坦堡", "country": "TUR"},
  {"en": "Ankara", "zh": "安卡拉", "country": "TUR"},
  {"en": "Antalya", "zh": "安塔利亚", "country": "TUR"},
  {"en": "Izmir", "zh": "伊兹密尔", "country": "TUR"},
  {"en": "Adana", "zh": "阿达纳", "country": "TUR"},
  {"en": "Trabzon", "zh": "特拉布宗", "country": "TUR"},
  {"en": "Bodrum", "zh": "博德鲁姆", "country": "TUR"},
  {"en": "Tehran", "zh": "德黑兰", "country": "IRN"},
  {"en": "Mashhad", "zh": "马什哈德", "country": "IRN"},
  {"en": "Shiraz", "zh": "设拉子", "country": "IRN"},
  {"en": "Isfahan", "zh": "伊斯法罕", "country": "IRN"},
  {"en": "Tabriz", "zh": "大不里士", "country": "IRN"},
  {"en": "London", "zh": "伦敦", "country": "GBR"},
  {"en": "Paris", "zh": "巴黎", "country": "FRA"},
  {"en": "Berlin", "zh": "柏林", "country": "DEU"},
  {"en": "Madrid", "zh": "马德里", "country": "ESP"},
  {"en": "Rome", "zh": "罗马", "country": "ITA"},
  {"en": "Lisbon", "zh": "里斯本", "country": "PRT"},
  {"en": "Amsterdam", "zh": "阿姆斯特丹", "country": "NLD"},
  {"en": "Brussels", "zh": "布鲁塞尔", "country": "BEL"},
  {"en": "Vienna", "zh": "维也纳", "country": "AUT"},
  {"en": "Bern", "zh": "伯尔尼", "hant": "伯恩", "country": "CHE"},
  {"en": "Dublin", "zh": "都柏林", "country": "IRL"},
  {"en": "Copenhagen", "zh": "哥本哈根", "country": "DNK"},
  {"en": "Stockholm", "zh": "斯德哥尔摩", "country": "SWE"},
  {"en": "Oslo", "zh": "奥斯陆", "country": "NOR"},
  {"en": "Helsinki", "zh": "赫尔辛基", "country": "FIN"},
  {"en": "Reykjavik", "zh": "雷克雅未克", "hant": "雷克雅維克", "country": "ISL"},
  {"en": "Warsaw", "zh": "华沙", "country": "POL"},
  {"en": "Prague", "zh": "布拉格", "country": "CZE"},
  {"en": "Bratislava", "zh": "布拉迪斯拉发", "hant": "布拉提斯拉瓦", "country": "SVK"},
  {"en": "Budapest", "zh": "布达佩斯", "country": "HUN"},
  {"en": "Bucharest", "zh": "布加勒斯特", "country": "ROU"},
  {"en": "Sofia", "zh": "索非亚", "hant": "索菲亞", "country": "BGR"},
  {"en": "Athens", "zh": "雅典", "country": "GRC"},
  {"en": "Belgrade", "zh": "贝尔格莱德", "hant": "貝爾格勒", "country": "SRB"},
  {"en": "Zagreb", "zh": "萨格勒布", "country": "HRV"},
  {"en": "Ljubljana", "zh": "卢布尔雅那", "hant": "盧比安納", "country": "SVN"},
  {"en": "Sarajevo", "zh": "萨拉热窝", "hant": "塞拉耶佛", "country": "BIH"},
  {"en": "Podgorica", "zh": "波德戈里察", "country": "MNE"},
  {"en": "Skopje", "zh": "斯科普里", "hant": "史高比耶", "country": "MKD"},
  {"en": "Tirana", "zh": "地拉那", "country": "ALB"},
  {"en": "Pristina", "zh": "普里什蒂纳", "country": "XKX"},
  {"en": "Nicosia", "zh": "尼科西亚", "country": "CYP"},
  {"en": "Valletta", "zh": "瓦莱塔", "country": "MLT"},
  {"en": "Tallinn", "zh": "塔林", "country": "EST"},
  {"en": "Riga", "zh": "里加", "country": "LVA"},
  {"en": "Vilnius", "zh": "维尔纽斯", "country": "LTU"},
  {"en": "Minsk", "zh": "明斯克", "country": "BLR"},
  {"en": "Kyiv", "zh": "基辅", "country": "UKR"},
  {"en": "Chisinau", "zh": "基希讷乌", "hant": "奇西瑙", "country": "MDA"},
  {"en": "Moscow", "zh": "莫斯科", "country": "RUS"},
  {"en": "Luxembourg", "zh": "卢森堡", "country": "LUX"},
  {"en": "Monaco", "zh": "摩纳哥", "country": "MCO"},
  {"en": "Andorra la Vella", "zh": "安道尔城", "country": "AND"},
  {"en": "San Marino", "zh": "圣马力诺", "hant": "聖馬利諾", "country": "SMR"},
  {"en": "Vatican City", "zh": "梵蒂冈", "hant": "梵蒂岡", "country": "VAT"},
  {"en": "Vaduz", "zh": "瓦杜兹", "country": "LIE"},
  {"en": "Manchester", "zh": "曼彻斯特", "country": "GBR"},
  {"en": "Birmingham", "zh": "伯明翰", "country": "GBR"},
  {"en": "Edinburgh", "zh": "爱丁堡", "country": "GBR"},
  {"en": "Glasgow", "zh": "格拉斯哥", "country": "GBR"},
  {"en": "Belfast", "zh": "贝尔法斯特", "country": "GBR"},
  {"en": "Nice", "zh": "尼斯", "country": "FRA"},
  {"en": "Lyon", "zh": "里昂", "country": "FRA"},
  {"en": "Marseille", "zh": "马赛", "country": "FRA"},
  {"en": "Toulouse", "zh": "图卢兹", "hant": "土魯斯", "country": "FRA"},
  {"en": "Frankfurt", "zh": "法兰克福", "country": "DEU"},
  {"en": "Munich", "zh": "慕尼黑", "country": "DEU"},
  {"en": "Hamburg", "zh": "汉堡", "country": "DEU"},
  {"en": "Dusseldorf", "zh": "杜塞尔多夫", "hant": "杜塞道夫", "country": "DEU"},
  {"en": "Cologne", "zh": "科隆", "country": "DEU"},
  {"en": "Stuttgart", "zh": "斯图加特", "country": "DEU"},
  {"en": "Zurich", "zh": "苏黎世", "country": "CHE"},
  {"en": "Geneva", "zh": "日内瓦", "country": "CHE"},
  {"en": "Basel", "zh": "巴塞尔", "country": "CHE"},
  {"en": "Salzburg", "zh": "萨尔茨堡", "hant": "薩爾斯堡", "country": "AUT"},
  {"en": "Barcelona", "zh": "巴塞罗那", "hant": "巴塞隆納", "country": "ESP"},
  {"en": "Malaga", "zh": "马拉加", "country": "ESP"},
  {"en": "Valencia", "zh": "瓦伦西亚", "country": "ESP"},
  {"en": "Seville", "zh": "塞维利亚", "hant": "塞維亞", "country": "ESP"},
  {"en": "Bilbao", "zh": "毕尔巴鄂", "hant": "畢爾包", "country": "ESP"},
  {"en": "Palma de Mallorca", "zh": "马略卡岛帕尔马", "country": "ESP"},
  {"en": "Alicante", "zh": "阿利坎特", "country": "ESP"},
  {"en": "Tenerife", "zh": "特内里费", "country": "ESP"},
  {"en": "Las Palmas", "zh": "拉斯帕尔马斯", "country": "ESP"},
  {"en": "Milan", "zh": "米兰", "country": "ITA"},
  {"en": "Venice", "zh": "威尼斯", "country": "ITA"},
  {"en": "Florence", "zh": "佛罗伦萨", "hant": "佛羅倫斯", "country": "ITA"},
  {"en": "Naples", "zh": "那不勒斯", "hant": "拿坡里", "country": "ITA"},
  {"en": "Bologna", "zh": "博洛尼亚", "hant": "波隆那", "country": "ITA"},
  {"en": "Turin", "zh": "都灵", "hant": "杜林", "country": "ITA"},
  {"en": "Porto", "zh": "波尔图", "country": "PRT"},
  {"en": "Gothenburg", "zh": "哥德堡", "country": "SWE"},
  {"en": "Bergen", "zh": "卑尔根", "country": "NOR"},
  {"en": "Saint Petersburg", "zh": "圣彼得堡", "country": "RUS"},
  {"en": "Krakow", "zh": "克拉科夫", "country": "POL"},
  {"en": "Gdansk", "zh": "格但斯克", "country": "POL"},
  {"en": "Thessaloniki", "zh": "塞萨洛尼基", "country": "GRC"},
  {"en": "Larnaca", "zh": "拉纳卡", "country": "CYP"},
  {"en": "Cairo", "zh": "开罗", "country": "EGY"},
  {"en": "Alexandria", "zh": "亚历山大", "hant": "亞歷山卓", "country": "EGY"},
  {"en": "Algiers", "zh": "阿尔及尔", "country": "DZA"},
  {"en": "Tunis", "zh": "突尼斯", "country": "TUN"},
  {"en": "Tripoli", "zh": "的黎波里", "country": "LBY"},
  {"en": "Rabat", "zh": "拉巴特", "country": "MAR"},
  {"en": "Casablanca", "zh": "卡萨布兰卡", "country": "MAR"},
  {"en": "Marrakesh", "zh": "马拉喀什", "country": "MAR"},
  {"en": "Nouakchott", "zh": "努瓦克肖特", "country": "MRT"},
  {"en": "Dakar", "zh": "达喀尔", "hant": "達卡", "country": "SEN"},
  {"en": "Banjul", "zh": "班珠尔", "country": "GMB"},
  {"en": "Bissau", "zh": "比绍", "country": "GNB"},
  {"en": "Conakry", "zh": "科纳克里", "country": "GIN"},
  {"en": "Freetown", "zh": "弗里敦", "country": "SLE"},
  {"en": "Monrovia", "zh": "蒙罗维亚", "country": "LBR"},
  {"en": "Yamoussoukro", "zh": "亚穆苏克罗", "country": "CIV"},
  {"en": "Abidjan", "zh": "阿比让", "hant": "阿必尚", "country": "CIV"},
  {"en": "Bamako", "zh": "巴马科", "country": "MLI"},
  {"en": "Ouagadougou", "zh": "瓦加杜古", "country": "BFA"},
  {"en": "Accra", "zh": "阿克拉", "country": "GHA"},
  {"en": "Lome", "zh": "洛美", "country": "TGO"},
  {"en": "Porto-Novo", "zh": "波多诺伏", "country": "BEN"},
  {"en": "Cotonou", "zh": "科托努", "country": "BEN"},
  {"en": "Niamey", "zh": "尼亚美", "country": "NER"},
  {"en": "Abuja", "zh": "阿布贾", "hant": "阿布加", "country": "NGA"},
  {"en": "Lagos", "zh": "拉各斯", "hant": "拉哥斯", "country": "NGA"},
  {"en": "Yaounde", "zh": "雅温得", "country": "CMR"},
  {"en": "Douala", "zh": "杜阿拉", "country": "CMR"},
  {"en": "Malabo", "zh": "马拉博", "country": "GNQ"},
  {"en": "Libreville", "zh": "利伯维尔", "country": "GAB"},
  {"en": "N'Djamena", "zh": "恩贾梅纳", "country": "TCD"},
  {"en": "Bangui", "zh": "班吉", "country": "CAF"},
  {"en": "Brazzaville", "zh": "布拉柴维尔", "country": "COG"},
  {"en": "Kinshasa", "zh": "金沙萨", "hant": "金夏沙", "country": "COD"},
  {"en": "Luanda", "zh": "罗安达", "country": "AGO"},
  {"en": "Windhoek", "zh": "温得和克", "country": "NAM"},
  {"en": "Gaborone", "zh": "哈博罗内", "hant": "嘉柏隆里", "country": "BWA"},
  {"en": "Pretoria", "zh": "比勒陀利亚", "country": "ZAF"},
  {"en": "Johannesburg", "zh": "约翰内斯堡", "hant": "約翰尼斯堡", "country": "ZAF"},
  {"en": "Cape Town", "zh": "开普敦", "country": "ZAF"},
  {"en": "Durban", "zh": "德班", "country": "ZAF"},
  {"en": "Maseru", "zh": "马塞卢", "hant": "馬賽魯", "country": "LSO"},
  {"en": "Mbabane", "zh": "姆巴巴内", "hant": "墨巴本", "country": "SWZ"},
  {"en": "Maputo", "zh": "马普托", "country": "MOZ"},
  {"en": "Harare", "zh": "哈拉雷", "country": "ZWE"},
  {"en": "Lusaka", "zh": "卢萨卡", "country": "ZMB"},
  {"en": "Lilongwe", "zh": "利隆圭", "country": "MWI"},
  {"en": "Antananarivo", "zh": "塔那那利佛", "country": "MDG"},
  {"en": "Port Louis", "zh": "路易港", "country": "MUS"},
  {"en": "Victoria", "zh": "维多利亚", "country": "SYC"},
  {"en": "Moroni", "zh": "莫罗尼", "country": "COM"},
  {"en": "Dar es Salaam", "zh": "达累斯萨拉姆", "hant": "三蘭港", "country": "TZA"},
  {"en": "Dodoma", "zh": "多多马", "country": "TZA"},
  {"en": "Nairobi", "zh": "内罗毕", "hant": "奈洛比", "country": "KEN"},
  {"en": "Mombasa", "zh": "蒙巴萨", "country": "KEN"},
  {"en": "Kampala", "zh": "坎帕拉", "country": "UGA"},
  {"en": "Kigali", "zh": "基加利", "country": "RWA"},
  {"en": "Bujumbura", "zh": "布琼布拉", "country": "BDI"},
  {"en": "Gitega", "zh": "基特加", "country": "BDI"},
  {"en": "Addis Ababa", "zh": "亚的斯亚贝巴", "hant": "阿迪斯阿貝巴", "country": "ETH"},
  {"en": "Djibouti", "zh": "吉布提", "hant": "吉布地", "country": "DJI"},
  {"en": "Asmara", "zh": "阿斯马拉", "country": "ERI"},
  {"en": "Mogadishu", "zh": "摩加迪沙", "hant": "摩加迪休", "country": "SOM"},
  {"en": "Khartoum", "zh": "喀土穆", "country": "SDN"},
  {"en": "Juba", "zh": "朱巴", "country": "SSD"},
  {"en": "Praia", "zh": "普拉亚", "country": "CPV"},
  {"en": "Sao Tome", "zh": "圣多美", "country": "STP"},
  {"en": "Washington, D.C.", "zh": "华盛顿", "country": "USA"},
  {"en": "New York", "zh": "纽约", "country": "USA"},
  {"en": "Los Angeles", "zh": "洛杉矶", "country": "USA"},
  {"en": "Chicago", "zh": "芝加哥", "country": "USA"},
  {"en": "San Francisco", "zh": "旧金山", "country": "USA"},
  {"en": "Seattle", "zh": "西雅图", "country": "USA"},
  {"en": "Boston", "zh": "波士顿", "country": "USA"},
  {"en": "Miami", "zh": "迈阿密", "country": "USA"},
  {"en": "Atlanta", "zh": "亚特兰大", "country": "USA"},
  {"en": "Dallas", "zh": "达拉斯", "country": "USA"},
  {"en": "Houston", "zh": "休斯敦", "hant": "休士頓", "country": "USA"},
  {"en": "Denver", "zh": "丹佛", "country": "USA"},
  {"en": "Las Vegas", "zh": "拉斯维加斯", "country": "USA"},
  {"en": "Orlando", "zh": "奥兰多", "country": "USA"},
  {"en": "Phoenix", "zh": "凤凰城", "country": "USA"},
  {"en": "Philadelphia", "zh": "费城", "country": "USA"},
  {"en": "Detroit", "zh": "底特律", "country": "USA"},
  {"en": "Minneapolis", "zh": "明尼阿波利斯", "hant": "明尼亞波利斯", "country": "USA"},
  {"en": "San Diego", "zh": "圣迭戈", "hant": "聖地牙哥", "country": "USA"},
  {"en": "San Jose", "zh": "圣何塞", "hant": "聖荷西", "country": "USA"},
  {"en": "Austin", "zh": "奥斯汀", "country": "USA"},
  {"en": "Portland", "zh": "波特兰", "country": "USA"},
  {"en": "Salt Lake City", "zh": "盐湖城", "country": "USA"},
  {"en": "Charlotte", "zh": "夏洛特", "country": "USA"},
  {"en": "Tampa", "zh": "坦帕", "country": "USA"},
  {"en": "Fort Lauderdale", "zh": "劳德代尔堡", "hant": "羅德岱堡", "country": "USA"},
  {"en": "Honolulu", "zh": "檀香山", "country": "USA"},
  {"en": "Anchorage", "zh": "安克雷奇", "hant": "安克拉治", "country": "USA"},
  {"en": "New Orleans", "zh": "新奥尔良", "hant": "紐奧良", "country": "USA"},
  {"en": "Nashville", "zh": "纳什维尔", "hant": "納許維爾", "country": "USA"},
  {"en": "Baltimore", "zh": "巴尔的摩", "country": "USA"},
  {"en": "Pittsburgh", "zh": "匹兹堡", "country": "USA"},
  {"en": "St. Louis", "zh": "圣路易斯", "hant": "聖路易", "country": "USA"},
  {"en": "Cincinnati", "zh": "辛辛那提", "country": "USA"},
  {"en": "Kansas City", "zh": "堪萨斯城", "country": "USA"},
  {"en": "Raleigh", "zh": "罗利", "country": "USA"},
  {"en": "Columbus", "zh": "哥伦布", "country": "USA"},
  {"en": "Indianapolis", "zh": "印第安纳波利斯", "country": "USA"},
  {"en": "Cleveland", "zh": "克利夫兰", "country": "USA"},
  {"en": "Sacramento", "zh": "萨克拉门托", "hant": "沙加緬度", "country": "USA"},
  {"en": "San Antonio", "zh": "圣安东尼奥", "country": "USA"},
  {"en": "San Juan", "zh": "圣胡安", "country": "PRI"},
  {"en": "Ottawa", "zh": "渥太华", "country": "CAN"},
  {"en": "Toronto", "zh": "多伦多", "country": "CAN"},
  {"en": "Montreal", "zh": "蒙特利尔", "hant": "蒙特婁", "country": "CAN"},
  {"en": "Vancouver", "zh": "温哥华", "country": "CAN"},
  {"en": "Calgary", "zh": "卡尔加里", "hant": "卡加利", "country": "CAN"},
  {"en": "Edmonton", "zh": "埃德蒙顿", "country": "CAN"},
  {"en": "Winnipeg", "zh": "温尼伯", "country": "CAN"},
  {"en": "Halifax", "zh": "哈利法克斯", "country": "CAN"},
  {"en": "Quebec City", "zh": "魁北克城", "country": "CAN"},
  {"en": "Mexico City", "zh": "墨西哥城", "country": "MEX"},
  {"en": "Cancun", "zh": "坎昆", "country": "MEX"},
  {"en": "Guadalajara", "zh": "瓜达拉哈拉", "country": "MEX"},
  {"en": "Monterrey", "zh": "蒙特雷", "country": "MEX"},
  {"en": "Tijuana", "zh": "蒂华纳", "hant": "提華納", "country": "MEX"},
  {"en": "Puerto Vallarta", "zh": "巴亚尔塔港", "country": "MEX"},
  {"en": "Los Cabos", "zh": "洛斯卡沃斯", "country": "MEX"},
  {"en": "Guatemala City", "zh": "危地马拉城", "hant": "瓜地馬拉市", "country": "GTM"},
  {"en": "Belmopan", "zh": "贝尔莫潘", "hant": "貝爾墨潘", "country": "BLZ"},
  {"en": "Belize City", "zh": "伯利兹城", "hant": "貝里斯市", "country": "BLZ"},
  {"en": "Tegucigalpa", "zh": "特古西加尔巴", "hant": "德古西加巴", "country": "HND"},
  {"en": "San Pedro Sula", "zh": "圣佩德罗苏拉", "country": "HND"},
  {"en": "San Salvador", "zh": "圣萨尔瓦多", "country": "SLV"},
  {"en": "Managua", "zh": "马那瓜", "hant": "馬納瓜", "country": "NIC"},
  {"en": "San Jose", "zh": "圣何塞", "hant": "聖荷西", "country": "CRI"},
  {"en": "Panama City", "zh": "巴拿马城", "hant": "巴拿馬市", "country": "PAN"},
  {"en": "Havana", "zh": "哈瓦那", "country": "CUB"},
  {"en": "Kingston", "zh": "金斯敦", "hant": "京斯敦", "country": "JAM"},
  {"en": "Montego Bay", "zh": "蒙特哥贝", "country": "JAM"},
  {"en": "Port-au-Prince", "zh": "太子港", "country": "HTI"},
  {"en": "Santo Domingo", "zh": "圣多明各", "hant": "聖多明哥", "country": "DOM"},
  {"en": "Punta Cana", "zh": "蓬塔卡纳", "country": "DOM"},
  {"en": "Nassau", "zh": "拿骚", "hant": "拿索", "country": "BHS"},
  {"en": "Bridgetown", "zh": "布里奇敦", "country": "BRB"},
  {"en": "Port of Spain", "zh": "西班牙港", "country": "TTO"},
  {"en": "Saint John's", "zh": "圣约翰", "country": "ATG"},
  {"en": "Castries", "zh": "卡斯特里", "hant": "卡斯翠", "country": "LCA"},
  {"en": "Saint George's", "zh": "圣乔治", "country": "GRD"},
  {"en": "Kingstown", "zh": "金斯敦", "hant": "金石城", "country": "VCT"},
  {"en": "Roseau", "zh": "罗索", "country": "DMA"},
  {"en": "Basseterre", "zh": "巴斯特尔", "country": "KNA"},
  {"en": "Buenos Aires", "zh": "布宜诺斯艾利斯", "country": "ARG"},
  {"en": "Santiago", "zh": "圣地亚哥", "hant": "聖地牙哥", "country": "CHL"},
  {"en": "Lima", "zh": "利马", "country": "PER"},
  {"en": "Cusco", "zh": "库斯科", "country": "PER"},
  {"en": "Bogota", "zh": "波哥大", "country": "COL"},
  {"en": "Medellin", "zh": "麦德林", "country": "COL"},
  {"en": "Cartagena", "zh": "卡塔赫纳", "country": "COL"},
  {"en": "Quito", "zh": "基多", "country": "ECU"},
  {"en": "Guayaquil", "zh": "瓜亚基尔", "country": "ECU"},
  {"en": "Caracas", "zh": "加拉加斯", "hant": "卡拉卡斯", "country": "VEN"},
  {"en": "Georgetown", "zh": "乔治敦", "country": "GUY"},
  {"en": "Paramaribo", "zh": "帕拉马里博", "country": "SUR"},
  {"en": "La Paz", "zh": "拉巴斯", "country": "BOL"},
  {"en": "Sucre", "zh": "苏克雷", "country": "BOL"},
  {"en": "Asuncion", "zh": "亚松森", "country": "PRY"},
  {"en": "Montevideo", "zh": "蒙得维的亚", "hant": "蒙特維多", "country": "URY"},
  {"en": "Brasilia", "zh": "巴西利亚", "country": "BRA"},
  {"en": "Sao Paulo", "zh": "圣保罗", "country": "BRA"},
  {"en": "Rio de Janeiro", "zh": "里约热内卢", "country": "BRA"},
  {"en": "Belo Horizonte", "zh": "贝洛奥里藏特", "country": "BRA"},
  {"en": "Salvador", "zh": "萨尔瓦多", "country": "BRA"},
  {"en": "Fortaleza", "zh": "福塔莱萨", "country": "BRA"},
  {"en": "Recife", "zh": "累西腓", "country": "BRA"},
  {"en": "Porto Alegre", "zh": "阿雷格里港", "country": "BRA"},
  {"en": "Manaus", "zh": "马瑙斯", "country": "BRA"},
  {"en": "Curitiba", "zh": "库里蒂巴", "country": "BRA"},
  {"en": "Canberra", "zh": "堪培拉", "hant": "坎培拉", "country": "AUS"},
  {"en": "Sydney", "zh": "悉尼", "hant": "雪梨", "country": "AUS"},
  {"en": "Melbourne", "zh": "墨尔本", "country": "AUS"},
  {"en": "Brisbane", "zh": "布里斯班", "hant": "布里斯本", "country": "AUS"},
  {"en": "Perth", "zh": "珀斯", "hant": "伯斯", "country": "AUS"},
  {"en": "Adelaide", "zh": "阿德莱德", "hant": "阿得雷德", "country": "AUS"},
  {"en": "Gold Coast", "zh": "黄金海岸", "country": "AUS"},
  {"en": "Cairns", "zh": "凯恩斯", "country": "AUS"},
  {"en": "Darwin", "zh": "达尔文", "country": "AUS"},
  {"en": "Hobart", "zh": "霍巴特", "country": "AUS"},
  {"en": "Wellington", "zh": "惠灵顿", "hant": "威靈頓", "country": "NZL"},
  {"en": "Auckland", "zh": "奥克兰", "country": "NZL"},
  {"en": "Christchurch", "zh": "克赖斯特彻奇", "hant": "基督城", "country": "NZL"},
  {"en": "Queenstown", "zh": "皇后镇", "country": "NZL"},
  {"en": "Suva", "zh": "苏瓦", "country": "FJI"},
  {"en": "Nadi", "zh": "楠迪", "hant": "南迪", "country": "FJI"},
  {"en": "Port Moresby", "zh": "莫尔兹比港", "hant": "莫士比港", "country": "PNG"},
  {"en": "Honiara", "zh": "霍尼亚拉", "hant": "荷尼阿拉", "country": "SLB"},
  {"en": "Port Vila", "zh": "维拉港", "country": "VUT"},
  {"en": "Apia", "zh": "阿皮亚", "country": "WSM"},
  {"en": "Nuku'alofa", "zh": "努库阿洛法", "hant": "努瓜婁發", "country": "TON"},
  {"en": "Tarawa", "zh": "塔拉瓦", "country": "KIR"},
  {"en": "Funafuti", "zh": "富纳富提", "country": "TUV"},
  {"en": "Yaren", "zh": "亚伦", "country": "NRU"},
  {"en": "Majuro", "zh": "马朱罗", "hant": "馬久羅", "country": "MHL"},
  {"en": "Palikir", "zh": "帕利基尔", "country": "FSM"},
  {"en": "Koror", "zh": "科罗尔", "country": "PLW"},
  {"en": "Papeete", "zh": "帕皮提", "country": "PYF"},
  {"en": "Noumea", "zh": "努美阿", "country": "NCL"}
]
