// Explicit workflow state machine. Every case has exactly one state; only
// declared transitions are legal, and human-interaction states (CAPTCHA, OTP,
// verification, payment, declaration) are first-class states, not failures.
//
// The orchestrator advances the machine; it never mutates `state` directly.

export const STATES = Object.freeze([
  'DRAFT', 'DATA_INCOMPLETE', 'READY_FOR_REVIEW', 'APPLICANT_REVIEW_REQUIRED',
  'AUTHORIZATION_REQUIRED', 'AUTHORIZATION_PENDING', 'AUTHORIZATION_SIGNED',
  'PORTAL_ACCOUNT_REQUIRED', 'PORTAL_ACCOUNT_CREATING', 'PORTAL_VERIFICATION_REQUIRED', 'PORTAL_ACCOUNT_READY',
  'PORTAL_LOGIN_REQUIRED', 'BROWSER_SESSION_PENDING', 'APPLICATION_FILLING', 'DOCUMENT_UPLOAD_PENDING',
  'CAPTCHA_ACTION_REQUIRED', 'OTP_ACTION_REQUIRED', 'IDENTITY_ACTION_REQUIRED',
  'FEE_DISCOVERY_PENDING', 'PAYMENT_APPROVAL_REQUIRED', 'PAYMENT_ACTION_REQUIRED', 'PAYMENT_PROCESSING', 'PAYMENT_COMPLETED',
  'APPOINTMENT_SEARCHING', 'APPOINTMENT_AVAILABLE', 'APPOINTMENT_BOOKING', 'APPOINTMENT_BOOKED',
  'EARLIER_APPOINTMENT_MONITORING', 'RESCHEDULE_APPROVAL_REQUIRED', 'APPOINTMENT_RESCHEDULING',
  'FINAL_REVIEW_REQUIRED', 'PERSONAL_DECLARATION_REQUIRED', 'READY_TO_SUBMIT', 'SUBMITTING', 'SUBMITTED',
  'CONFIRMATION_PENDING', 'COMPLETED', 'RECOVERABLE_FAILURE', 'MANUAL_REVIEW_REQUIRED', 'CANCELLED'
])

const S = Object.fromEntries(STATES.map((s) => [s, s]))

// Allowed transitions. Any state may go to RECOVERABLE_FAILURE, MANUAL_REVIEW_
// REQUIRED, or CANCELLED (added programmatically below).
const TRANSITIONS = {
  DRAFT: ['DATA_INCOMPLETE', 'READY_FOR_REVIEW'],
  DATA_INCOMPLETE: ['READY_FOR_REVIEW', 'DRAFT'],
  READY_FOR_REVIEW: ['APPLICANT_REVIEW_REQUIRED'],
  APPLICANT_REVIEW_REQUIRED: ['AUTHORIZATION_REQUIRED', 'DATA_INCOMPLETE'],
  AUTHORIZATION_REQUIRED: ['AUTHORIZATION_PENDING'],
  AUTHORIZATION_PENDING: ['AUTHORIZATION_SIGNED', 'AUTHORIZATION_REQUIRED'],
  AUTHORIZATION_SIGNED: ['PORTAL_ACCOUNT_REQUIRED'],
  PORTAL_ACCOUNT_REQUIRED: ['PORTAL_ACCOUNT_CREATING', 'PORTAL_LOGIN_REQUIRED'],
  PORTAL_ACCOUNT_CREATING: ['PORTAL_VERIFICATION_REQUIRED', 'CAPTCHA_ACTION_REQUIRED', 'PORTAL_ACCOUNT_READY'],
  PORTAL_VERIFICATION_REQUIRED: ['PORTAL_ACCOUNT_READY', 'OTP_ACTION_REQUIRED', 'IDENTITY_ACTION_REQUIRED'],
  PORTAL_ACCOUNT_READY: ['PORTAL_LOGIN_REQUIRED', 'APPLICATION_FILLING'],
  PORTAL_LOGIN_REQUIRED: ['BROWSER_SESSION_PENDING', 'CAPTCHA_ACTION_REQUIRED', 'OTP_ACTION_REQUIRED', 'APPLICATION_FILLING'],
  BROWSER_SESSION_PENDING: ['APPLICATION_FILLING', 'PORTAL_LOGIN_REQUIRED'],
  APPLICATION_FILLING: ['DOCUMENT_UPLOAD_PENDING', 'CAPTCHA_ACTION_REQUIRED', 'FEE_DISCOVERY_PENDING'],
  DOCUMENT_UPLOAD_PENDING: ['FEE_DISCOVERY_PENDING', 'APPLICATION_FILLING'],
  CAPTCHA_ACTION_REQUIRED: ['PORTAL_ACCOUNT_CREATING', 'PORTAL_VERIFICATION_REQUIRED', 'PORTAL_LOGIN_REQUIRED', 'APPLICATION_FILLING', 'APPOINTMENT_BOOKING', 'PORTAL_ACCOUNT_READY'],
  OTP_ACTION_REQUIRED: ['PORTAL_VERIFICATION_REQUIRED', 'PORTAL_ACCOUNT_READY', 'APPLICATION_FILLING'],
  IDENTITY_ACTION_REQUIRED: ['PORTAL_ACCOUNT_READY', 'APPLICATION_FILLING'],
  FEE_DISCOVERY_PENDING: ['PAYMENT_APPROVAL_REQUIRED'],
  // A fee pause recorded while the live page still shows questions/CAPTCHA
  // reclassifies itself: reversible rewind to fee discovery (Python twin
  // app/statemachine.py carries the same transition).
  PAYMENT_APPROVAL_REQUIRED: ['PAYMENT_ACTION_REQUIRED', 'PAYMENT_PROCESSING', 'FEE_DISCOVERY_PENDING'],
  PAYMENT_ACTION_REQUIRED: ['PAYMENT_PROCESSING', 'PAYMENT_COMPLETED', 'PAYMENT_APPROVAL_REQUIRED'],
  PAYMENT_PROCESSING: ['PAYMENT_COMPLETED', 'PAYMENT_ACTION_REQUIRED', 'PAYMENT_APPROVAL_REQUIRED', 'RECOVERABLE_FAILURE'],
  PAYMENT_COMPLETED: ['APPOINTMENT_SEARCHING', 'FINAL_REVIEW_REQUIRED'],
  APPOINTMENT_SEARCHING: ['APPOINTMENT_AVAILABLE', 'EARLIER_APPOINTMENT_MONITORING'],
  APPOINTMENT_AVAILABLE: ['APPOINTMENT_BOOKING', 'APPOINTMENT_SEARCHING'],
  APPOINTMENT_BOOKING: ['APPOINTMENT_BOOKED', 'CAPTCHA_ACTION_REQUIRED', 'APPOINTMENT_AVAILABLE', 'RECOVERABLE_FAILURE'],
  APPOINTMENT_BOOKED: ['EARLIER_APPOINTMENT_MONITORING', 'RESCHEDULE_APPROVAL_REQUIRED', 'APPOINTMENT_RESCHEDULING', 'FINAL_REVIEW_REQUIRED'],
  EARLIER_APPOINTMENT_MONITORING: ['RESCHEDULE_APPROVAL_REQUIRED', 'APPOINTMENT_RESCHEDULING', 'APPOINTMENT_BOOKED', 'FINAL_REVIEW_REQUIRED'],
  RESCHEDULE_APPROVAL_REQUIRED: ['APPOINTMENT_RESCHEDULING', 'APPOINTMENT_BOOKED'],
  APPOINTMENT_RESCHEDULING: ['APPOINTMENT_BOOKED', 'RECOVERABLE_FAILURE'],
  FINAL_REVIEW_REQUIRED: ['PERSONAL_DECLARATION_REQUIRED', 'READY_TO_SUBMIT'],
  PERSONAL_DECLARATION_REQUIRED: ['READY_TO_SUBMIT'],
  READY_TO_SUBMIT: ['SUBMITTING'],
  SUBMITTING: ['SUBMITTED', 'CONFIRMATION_PENDING', 'RECOVERABLE_FAILURE'],
  SUBMITTED: ['CONFIRMATION_PENDING', 'COMPLETED'],
  CONFIRMATION_PENDING: ['COMPLETED', 'RECOVERABLE_FAILURE'],
  COMPLETED: [],
  RECOVERABLE_FAILURE: ['MANUAL_REVIEW_REQUIRED'], // plus resume targets added below
  MANUAL_REVIEW_REQUIRED: [],
  CANCELLED: []
}

// Every non-terminal state can escape to failure/manual/cancel.
const ESCAPES = ['RECOVERABLE_FAILURE', 'MANUAL_REVIEW_REQUIRED', 'CANCELLED']
for (const s of STATES) {
  if (['COMPLETED', 'CANCELLED', 'MANUAL_REVIEW_REQUIRED'].includes(s)) continue
  TRANSITIONS[s] = [...new Set([...(TRANSITIONS[s] || []), ...ESCAPES])]
}
// RECOVERABLE_FAILURE can resume to any handoff/work state after reconciliation.
TRANSITIONS.RECOVERABLE_FAILURE = [...new Set([...TRANSITIONS.RECOVERABLE_FAILURE,
  'PORTAL_LOGIN_REQUIRED', 'APPLICATION_FILLING', 'DOCUMENT_UPLOAD_PENDING',
  'FEE_DISCOVERY_PENDING', 'PAYMENT_ACTION_REQUIRED', 'PAYMENT_APPROVAL_REQUIRED',
  'APPOINTMENT_SEARCHING', 'APPOINTMENT_BOOKING', 'SUBMITTING', 'CONFIRMATION_PENDING'])]

export const HUMAN_HANDOFF_STATES = Object.freeze([
  'CAPTCHA_ACTION_REQUIRED', 'OTP_ACTION_REQUIRED', 'IDENTITY_ACTION_REQUIRED',
  'PORTAL_VERIFICATION_REQUIRED', 'PAYMENT_ACTION_REQUIRED', 'PERSONAL_DECLARATION_REQUIRED',
  'APPLICANT_REVIEW_REQUIRED', 'AUTHORIZATION_REQUIRED', 'RESCHEDULE_APPROVAL_REQUIRED'
])

export const TERMINAL_STATES = Object.freeze(['COMPLETED', 'CANCELLED', 'MANUAL_REVIEW_REQUIRED'])

export function canTransition(from, to) {
  if (!STATES.includes(from) || !STATES.includes(to)) return false
  return (TRANSITIONS[from] || []).includes(to)
}

export function isHandoff(state) { return HUMAN_HANDOFF_STATES.includes(state) }
export function isTerminal(state) { return TERMINAL_STATES.includes(state) }

/** A minimal case machine that records an append-only transition history. */
export class CaseMachine {
  constructor(initial = 'DRAFT', clock = () => Date.now()) {
    if (!STATES.includes(initial)) throw new Error(`invalid initial state ${initial}`)
    this.state = initial
    this.clock = clock
    this.history = [{ state: initial, at: clock(), reason: 'created' }]
  }

  transition(to, reason = '') {
    if (!canTransition(this.state, to)) {
      const e = new Error(`illegal transition ${this.state} -> ${to}`)
      e.code = 'ILLEGAL_TRANSITION'
      throw e
    }
    this.state = to
    this.history.push({ state: to, at: this.clock(), reason })
    return to
  }

  is(state) { return this.state === state }
}
