"""Workflow state machine — Python port of the tested JS machine. Same 40 states,
same guarded transitions, same first-class human-handoff states."""
from __future__ import annotations

STATES = [
    "DRAFT", "DATA_INCOMPLETE", "READY_FOR_REVIEW", "APPLICANT_REVIEW_REQUIRED",
    "AUTHORIZATION_REQUIRED", "AUTHORIZATION_PENDING", "AUTHORIZATION_SIGNED",
    "PORTAL_ACCOUNT_REQUIRED", "PORTAL_ACCOUNT_CREATING", "PORTAL_VERIFICATION_REQUIRED", "PORTAL_ACCOUNT_READY",
    "PORTAL_LOGIN_REQUIRED", "BROWSER_SESSION_PENDING", "APPLICATION_FILLING", "DOCUMENT_UPLOAD_PENDING",
    "CAPTCHA_ACTION_REQUIRED", "OTP_ACTION_REQUIRED", "IDENTITY_ACTION_REQUIRED",
    "FEE_DISCOVERY_PENDING", "PAYMENT_APPROVAL_REQUIRED", "PAYMENT_ACTION_REQUIRED", "PAYMENT_PROCESSING", "PAYMENT_COMPLETED",
    "APPOINTMENT_SEARCHING", "APPOINTMENT_AVAILABLE", "APPOINTMENT_BOOKING", "APPOINTMENT_BOOKED",
    "EARLIER_APPOINTMENT_MONITORING", "RESCHEDULE_APPROVAL_REQUIRED", "APPOINTMENT_RESCHEDULING",
    "FINAL_REVIEW_REQUIRED", "PERSONAL_DECLARATION_REQUIRED", "READY_TO_SUBMIT", "SUBMITTING", "SUBMITTED",
    "CONFIRMATION_PENDING", "COMPLETED", "RECOVERABLE_FAILURE", "MANUAL_REVIEW_REQUIRED", "CANCELLED",
]

_T = {
    "DRAFT": ["DATA_INCOMPLETE", "READY_FOR_REVIEW"],
    "DATA_INCOMPLETE": ["READY_FOR_REVIEW", "DRAFT"],
    "READY_FOR_REVIEW": ["APPLICANT_REVIEW_REQUIRED"],
    "APPLICANT_REVIEW_REQUIRED": ["AUTHORIZATION_REQUIRED", "DATA_INCOMPLETE"],
    "AUTHORIZATION_REQUIRED": ["AUTHORIZATION_PENDING"],
    "AUTHORIZATION_PENDING": ["AUTHORIZATION_SIGNED", "AUTHORIZATION_REQUIRED"],
    "AUTHORIZATION_SIGNED": ["PORTAL_ACCOUNT_REQUIRED"],
    "PORTAL_ACCOUNT_REQUIRED": ["PORTAL_ACCOUNT_CREATING", "PORTAL_LOGIN_REQUIRED"],
    "PORTAL_ACCOUNT_CREATING": ["PORTAL_VERIFICATION_REQUIRED", "CAPTCHA_ACTION_REQUIRED", "PORTAL_ACCOUNT_READY"],
    "PORTAL_VERIFICATION_REQUIRED": ["PORTAL_ACCOUNT_READY", "OTP_ACTION_REQUIRED", "IDENTITY_ACTION_REQUIRED"],
    "PORTAL_ACCOUNT_READY": ["PORTAL_LOGIN_REQUIRED", "APPLICATION_FILLING"],
    "PORTAL_LOGIN_REQUIRED": ["BROWSER_SESSION_PENDING", "CAPTCHA_ACTION_REQUIRED", "OTP_ACTION_REQUIRED", "APPLICATION_FILLING"],
    "BROWSER_SESSION_PENDING": ["APPLICATION_FILLING", "PORTAL_LOGIN_REQUIRED"],
    "APPLICATION_FILLING": ["DOCUMENT_UPLOAD_PENDING", "CAPTCHA_ACTION_REQUIRED", "FEE_DISCOVERY_PENDING"],
    # Real portals can demand a CAPTCHA at the upload/fee stages too.
    "DOCUMENT_UPLOAD_PENDING": ["FEE_DISCOVERY_PENDING", "APPLICATION_FILLING", "CAPTCHA_ACTION_REQUIRED"],
    "CAPTCHA_ACTION_REQUIRED": ["PORTAL_ACCOUNT_CREATING", "PORTAL_VERIFICATION_REQUIRED", "PORTAL_LOGIN_REQUIRED", "APPLICATION_FILLING", "APPOINTMENT_BOOKING", "PORTAL_ACCOUNT_READY", "DOCUMENT_UPLOAD_PENDING", "FEE_DISCOVERY_PENDING"],
    "OTP_ACTION_REQUIRED": ["PORTAL_VERIFICATION_REQUIRED", "PORTAL_ACCOUNT_READY", "APPLICATION_FILLING"],
    "IDENTITY_ACTION_REQUIRED": ["PORTAL_ACCOUNT_READY", "APPLICATION_FILLING"],
    "FEE_DISCOVERY_PENDING": ["PAYMENT_APPROVAL_REQUIRED", "CAPTCHA_ACTION_REQUIRED"],
    "PAYMENT_APPROVAL_REQUIRED": ["PAYMENT_ACTION_REQUIRED", "PAYMENT_PROCESSING"],
    "PAYMENT_ACTION_REQUIRED": ["PAYMENT_PROCESSING", "PAYMENT_COMPLETED", "PAYMENT_APPROVAL_REQUIRED"],
    "PAYMENT_PROCESSING": ["PAYMENT_COMPLETED", "PAYMENT_ACTION_REQUIRED", "PAYMENT_APPROVAL_REQUIRED", "RECOVERABLE_FAILURE"],
    "PAYMENT_COMPLETED": ["APPOINTMENT_SEARCHING", "FINAL_REVIEW_REQUIRED"],
    "APPOINTMENT_SEARCHING": ["APPOINTMENT_AVAILABLE", "EARLIER_APPOINTMENT_MONITORING"],
    "APPOINTMENT_AVAILABLE": ["APPOINTMENT_BOOKING", "APPOINTMENT_SEARCHING"],
    "APPOINTMENT_BOOKING": ["APPOINTMENT_BOOKED", "CAPTCHA_ACTION_REQUIRED", "APPOINTMENT_AVAILABLE", "RECOVERABLE_FAILURE"],
    "APPOINTMENT_BOOKED": ["EARLIER_APPOINTMENT_MONITORING", "RESCHEDULE_APPROVAL_REQUIRED", "APPOINTMENT_RESCHEDULING", "FINAL_REVIEW_REQUIRED"],
    "EARLIER_APPOINTMENT_MONITORING": ["RESCHEDULE_APPROVAL_REQUIRED", "APPOINTMENT_RESCHEDULING", "APPOINTMENT_BOOKED", "FINAL_REVIEW_REQUIRED"],
    "RESCHEDULE_APPROVAL_REQUIRED": ["APPOINTMENT_RESCHEDULING", "APPOINTMENT_BOOKED"],
    "APPOINTMENT_RESCHEDULING": ["APPOINTMENT_BOOKED", "RECOVERABLE_FAILURE"],
    "FINAL_REVIEW_REQUIRED": ["PERSONAL_DECLARATION_REQUIRED", "READY_TO_SUBMIT"],
    "PERSONAL_DECLARATION_REQUIRED": ["READY_TO_SUBMIT"],
    "READY_TO_SUBMIT": ["SUBMITTING"],
    "SUBMITTING": ["SUBMITTED", "CONFIRMATION_PENDING", "RECOVERABLE_FAILURE"],
    "SUBMITTED": ["CONFIRMATION_PENDING", "COMPLETED"],
    "CONFIRMATION_PENDING": ["COMPLETED", "RECOVERABLE_FAILURE"],
    "COMPLETED": [],
    "RECOVERABLE_FAILURE": ["MANUAL_REVIEW_REQUIRED"],
    "MANUAL_REVIEW_REQUIRED": [],
    "CANCELLED": [],
}

_ESCAPES = ["RECOVERABLE_FAILURE", "MANUAL_REVIEW_REQUIRED", "CANCELLED"]
for _s in STATES:
    if _s in ("COMPLETED", "CANCELLED", "MANUAL_REVIEW_REQUIRED"):
        continue
    _T[_s] = sorted(set(_T.get(_s, []) + _ESCAPES))
_T["RECOVERABLE_FAILURE"] = sorted(set(_T["RECOVERABLE_FAILURE"] + [
    "PORTAL_LOGIN_REQUIRED", "APPLICATION_FILLING", "PAYMENT_ACTION_REQUIRED", "PAYMENT_APPROVAL_REQUIRED",
    "APPOINTMENT_SEARCHING", "APPOINTMENT_BOOKING", "SUBMITTING", "CONFIRMATION_PENDING"]))

HUMAN_HANDOFF_STATES = {
    "CAPTCHA_ACTION_REQUIRED", "OTP_ACTION_REQUIRED", "IDENTITY_ACTION_REQUIRED",
    "PORTAL_VERIFICATION_REQUIRED", "PAYMENT_ACTION_REQUIRED", "PERSONAL_DECLARATION_REQUIRED",
    "APPLICANT_REVIEW_REQUIRED", "AUTHORIZATION_REQUIRED", "RESCHEDULE_APPROVAL_REQUIRED",
}
TERMINAL_STATES = {"COMPLETED", "CANCELLED", "MANUAL_REVIEW_REQUIRED"}


class IllegalTransition(Exception):
    pass


def can_transition(frm: str, to: str) -> bool:
    return frm in STATES and to in STATES and to in _T.get(frm, [])


def is_handoff(state: str) -> bool:
    return state in HUMAN_HANDOFF_STATES


def is_terminal(state: str) -> bool:
    return state in TERMINAL_STATES


class CaseMachine:
    def __init__(self, state: str = "DRAFT", history: list | None = None):
        if state not in STATES:
            raise ValueError(f"invalid state {state}")
        self.state = state
        self.history = history or [{"state": state, "reason": "created"}]

    def transition(self, to: str, reason: str = "") -> str:
        if not can_transition(self.state, to):
            raise IllegalTransition(f"illegal transition {self.state} -> {to}")
        self.state = to
        self.history.append({"state": to, "reason": reason})
        return to
