"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
"""
from alembic import op
import sqlalchemy as sa


revision = '4ff4920431fd'
down_revision = '984526c3b1f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('on_demand_route_research_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('intake_id', sa.String(length=32), nullable=True),
    sa.Column('route_key', sa.String(length=400), nullable=False),
    sa.Column('route', sa.JSON(), nullable=False),
    sa.Column('requested_language', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('stage', sa.String(length=48), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(length=40), nullable=False),
    sa.Column('finished_at', sa.String(length=40), nullable=False),
    sa.Column('researched_at_date', sa.String(length=10), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('counters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('kimi_model', sa.String(length=64), nullable=False),
    sa.Column('extraction_version', sa.String(length=24), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_on_demand_route_research_jobs_intake_id'), 'on_demand_route_research_jobs', ['intake_id'], unique=False)
    op.create_index(op.f('ix_on_demand_route_research_jobs_org_id'), 'on_demand_route_research_jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_on_demand_route_research_jobs_route_key'), 'on_demand_route_research_jobs', ['route_key'], unique=False)
    op.create_index(op.f('ix_on_demand_route_research_jobs_stage'), 'on_demand_route_research_jobs', ['stage'], unique=False)
    op.create_index(op.f('ix_on_demand_route_research_jobs_status'), 'on_demand_route_research_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_on_demand_route_research_jobs_status'), table_name='on_demand_route_research_jobs')
    op.drop_index(op.f('ix_on_demand_route_research_jobs_stage'), table_name='on_demand_route_research_jobs')
    op.drop_index(op.f('ix_on_demand_route_research_jobs_route_key'), table_name='on_demand_route_research_jobs')
    op.drop_index(op.f('ix_on_demand_route_research_jobs_org_id'), table_name='on_demand_route_research_jobs')
    op.drop_index(op.f('ix_on_demand_route_research_jobs_intake_id'), table_name='on_demand_route_research_jobs')
    op.drop_table('on_demand_route_research_jobs')
    # ### end Alembic commands ###
