"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
"""
from alembic import op
import sqlalchemy as sa


revision = '949b2638a102'
down_revision = '4ff4920431fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browser_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('provider_session_id', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_sessions_application_id'), 'browser_sessions', ['application_id'], unique=False)
    op.create_index(op.f('ix_browser_sessions_org_id'), 'browser_sessions', ['org_id'], unique=False)
    op.create_index(op.f('ix_browser_sessions_status'), 'browser_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_browser_sessions_status'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_sessions_org_id'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_sessions_application_id'), table_name='browser_sessions')
    op.drop_table('browser_sessions')
    # ### end Alembic commands ###
