"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
"""
from alembic import op
import sqlalchemy as sa


revision = '984526c3b1f6'
down_revision = 'b8a9508310a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_intakes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('preferred_language', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('resolution_id', sa.String(length=32), nullable=True),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolution_id'], ['route_resolutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_intakes_org_id'), 'route_intakes', ['org_id'], unique=False)
    op.create_index(op.f('ix_route_intakes_status'), 'route_intakes', ['status'], unique=False)
    op.create_index(op.f('ix_route_intakes_user_id'), 'route_intakes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_intakes_user_id'), table_name='route_intakes')
    op.drop_index(op.f('ix_route_intakes_status'), table_name='route_intakes')
    op.drop_index(op.f('ix_route_intakes_org_id'), table_name='route_intakes')
    op.drop_table('route_intakes')
    # ### end Alembic commands ###
