"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
"""
from alembic import op
import sqlalchemy as sa


revision = 'b8a9508310a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_visa_centers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('destination_country', sa.String(length=3), nullable=False),
    sa.Column('residence_jurisdiction', sa.String(length=3), nullable=False),
    sa.Column('operator', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('official_linking_source', sa.String(length=500), nullable=False),
    sa.Column('verification_status', sa.String(length=48), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorized_visa_centers_destination_country'), 'authorized_visa_centers', ['destination_country'], unique=False)
    op.create_index(op.f('ix_authorized_visa_centers_snapshot_date'), 'authorized_visa_centers', ['snapshot_date'], unique=False)
    op.create_table('consular_jurisdiction_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('destination_country', sa.String(length=3), nullable=False),
    sa.Column('residence_jurisdiction', sa.String(length=3), nullable=False),
    sa.Column('residence_subdivisions', sa.JSON(), nullable=False),
    sa.Column('competent_post_name', sa.String(length=300), nullable=False),
    sa.Column('competent_post_kind', sa.String(length=32), nullable=False),
    sa.Column('competent_post_url', sa.String(length=500), nullable=False),
    sa.Column('covers_nationalities', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consular_jurisdiction_rules_destination_country'), 'consular_jurisdiction_rules', ['destination_country'], unique=False)
    op.create_index(op.f('ix_consular_jurisdiction_rules_residence_jurisdiction'), 'consular_jurisdiction_rules', ['residence_jurisdiction'], unique=False)
    op.create_index(op.f('ix_consular_jurisdiction_rules_snapshot_date'), 'consular_jurisdiction_rules', ['snapshot_date'], unique=False)
    op.create_table('human_review_tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('subject_id', sa.String(length=400), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('resolved_by', sa.String(length=120), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_review_tasks_kind'), 'human_review_tasks', ['kind'], unique=False)
    op.create_index(op.f('ix_human_review_tasks_org_id'), 'human_review_tasks', ['org_id'], unique=False)
    op.create_index(op.f('ix_human_review_tasks_snapshot_date'), 'human_review_tasks', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_human_review_tasks_status'), 'human_review_tasks', ['status'], unique=False)
    op.create_table('official_portals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('portal_uid', sa.String(length=160), nullable=False),
    sa.Column('destination_country', sa.String(length=3), nullable=False),
    sa.Column('portal_kind', sa.String(length=48), nullable=False),
    sa.Column('operator', sa.String(length=300), nullable=False),
    sa.Column('operator_kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('hostnames', sa.JSON(), nullable=False),
    sa.Column('allowed_redirect_hosts', sa.JSON(), nullable=False),
    sa.Column('official_linking_source', sa.String(length=500), nullable=False),
    sa.Column('supported_categories', sa.JSON(), nullable=False),
    sa.Column('verification_status', sa.String(length=48), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_official_portals_destination_country'), 'official_portals', ['destination_country'], unique=False)
    op.create_index(op.f('ix_official_portals_portal_uid'), 'official_portals', ['portal_uid'], unique=True)
    op.create_index(op.f('ix_official_portals_snapshot_date'), 'official_portals', ['snapshot_date'], unique=False)
    op.create_table('route_readiness_evaluations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('route_key', sa.String(length=400), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('readiness_status', sa.String(length=48), nullable=False),
    sa.Column('gates', sa.JSON(), nullable=False),
    sa.Column('evaluated_by', sa.String(length=120), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_readiness_evaluations_org_id'), 'route_readiness_evaluations', ['org_id'], unique=False)
    op.create_index(op.f('ix_route_readiness_evaluations_route_key'), 'route_readiness_evaluations', ['route_key'], unique=False)
    op.create_table('snapshot_conflicts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('route_key', sa.String(length=400), nullable=False),
    sa.Column('destination_country', sa.String(length=3), nullable=False),
    sa.Column('field', sa.String(length=120), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_conflicts_destination_country'), 'snapshot_conflicts', ['destination_country'], unique=False)
    op.create_index(op.f('ix_snapshot_conflicts_route_key'), 'snapshot_conflicts', ['route_key'], unique=False)
    op.create_index(op.f('ix_snapshot_conflicts_snapshot_date'), 'snapshot_conflicts', ['snapshot_date'], unique=False)
    op.create_table('snapshot_passport_validity_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('destination_country', sa.String(length=3), nullable=False),
    sa.Column('visa_category', sa.String(length=48), nullable=False),
    sa.Column('rule_kind', sa.String(length=48), nullable=False),
    sa.Column('months', sa.Float(), nullable=True),
    sa.Column('min_blank_pages', sa.Integer(), nullable=True),
    sa.Column('condition_text', sa.Text(), nullable=False),
    sa.Column('research_status', sa.String(length=32), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_passport_validity_rules_destination_country'), 'snapshot_passport_validity_rules', ['destination_country'], unique=False)
    op.create_index(op.f('ix_snapshot_passport_validity_rules_snapshot_date'), 'snapshot_passport_validity_rules', ['snapshot_date'], unique=False)
    op.create_table('snapshot_research_batches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('batch_key', sa.String(length=200), nullable=False),
    sa.Column('destination_country', sa.String(length=3), nullable=False),
    sa.Column('nationality_group', sa.String(length=120), nullable=False),
    sa.Column('residence_group', sa.String(length=120), nullable=False),
    sa.Column('stage', sa.String(length=48), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('conflict_count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(length=40), nullable=False),
    sa.Column('completed_at', sa.String(length=40), nullable=False),
    sa.Column('result', sa.String(length=48), nullable=False),
    sa.Column('content_hashes', sa.JSON(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'batch_key', name='uq_batch_key')
    )
    op.create_index(op.f('ix_snapshot_research_batches_batch_key'), 'snapshot_research_batches', ['batch_key'], unique=False)
    op.create_index(op.f('ix_snapshot_research_batches_destination_country'), 'snapshot_research_batches', ['destination_country'], unique=False)
    op.create_index(op.f('ix_snapshot_research_batches_snapshot_date'), 'snapshot_research_batches', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_snapshot_research_batches_stage'), 'snapshot_research_batches', ['stage'], unique=False)
    op.create_table('source_evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('original_url', sa.String(length=1000), nullable=False),
    sa.Column('final_url', sa.String(length=1000), nullable=False),
    sa.Column('redirect_chain', sa.JSON(), nullable=False),
    sa.Column('final_hostname', sa.String(length=300), nullable=False),
    sa.Column('source_authority', sa.String(length=64), nullable=False),
    sa.Column('applicable_jurisdiction', sa.String(length=120), nullable=False),
    sa.Column('relevant_excerpt', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.String(length=40), nullable=False),
    sa.Column('effective_date_evidence', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('page_language', sa.String(length=16), nullable=False),
    sa.Column('translation_reference', sa.String(length=120), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_evidence_content_hash'), 'source_evidence', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_evidence_final_hostname'), 'source_evidence', ['final_hostname'], unique=False)
    op.create_index(op.f('ix_source_evidence_snapshot_date'), 'source_evidence', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_source_evidence_source_authority'), 'source_evidence', ['source_authority'], unique=False)
    op.create_table('visa_fee_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('fee_uid', sa.String(length=160), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('destination_country', sa.String(length=3), nullable=False),
    sa.Column('visa_category', sa.String(length=48), nullable=False),
    sa.Column('record', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fee_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fee_uid', 'version', name='uq_fee_version')
    )
    op.create_index(op.f('ix_visa_fee_versions_content_hash'), 'visa_fee_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_visa_fee_versions_destination_country'), 'visa_fee_versions', ['destination_country'], unique=False)
    op.create_index(op.f('ix_visa_fee_versions_fee_uid'), 'visa_fee_versions', ['fee_uid'], unique=False)
    op.create_index(op.f('ix_visa_fee_versions_snapshot_date'), 'visa_fee_versions', ['snapshot_date'], unique=False)
    op.create_table('visa_policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('policy_uid', sa.String(length=120), nullable=False),
    sa.Column('destination_country', sa.String(length=3), nullable=False),
    sa.Column('policy_kind', sa.String(length=48), nullable=False),
    sa.Column('policy_name', sa.String(length=300), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('research_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visa_policies_destination_country'), 'visa_policies', ['destination_country'], unique=False)
    op.create_index(op.f('ix_visa_policies_policy_uid'), 'visa_policies', ['policy_uid'], unique=True)
    op.create_index(op.f('ix_visa_policies_snapshot_date'), 'visa_policies', ['snapshot_date'], unique=False)
    op.create_table('visa_routes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('route_key', sa.String(length=400), nullable=False),
    sa.Column('passport_nationality', sa.String(length=3), nullable=False),
    sa.Column('passport_issuing_country', sa.String(length=3), nullable=False),
    sa.Column('travel_document_type', sa.String(length=48), nullable=False),
    sa.Column('lawful_country_of_residence', sa.String(length=3), nullable=False),
    sa.Column('destination_country', sa.String(length=3), nullable=False),
    sa.Column('visa_category', sa.String(length=48), nullable=False),
    sa.Column('visa_subtype', sa.String(length=48), nullable=False),
    sa.Column('travel_purpose', sa.String(length=24), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('disposition', sa.String(length=48), nullable=False),
    sa.Column('research_status', sa.String(length=32), nullable=False),
    sa.Column('human_review_status', sa.String(length=32), nullable=False),
    sa.Column('fee_status', sa.String(length=24), nullable=False),
    sa.Column('portal_verification_status', sa.String(length=24), nullable=False),
    sa.Column('adapter_status', sa.String(length=32), nullable=False),
    sa.Column('conflict_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visa_routes_destination_country'), 'visa_routes', ['destination_country'], unique=False)
    op.create_index(op.f('ix_visa_routes_disposition'), 'visa_routes', ['disposition'], unique=False)
    op.create_index(op.f('ix_visa_routes_lawful_country_of_residence'), 'visa_routes', ['lawful_country_of_residence'], unique=False)
    op.create_index(op.f('ix_visa_routes_passport_issuing_country'), 'visa_routes', ['passport_issuing_country'], unique=False)
    op.create_index(op.f('ix_visa_routes_passport_nationality'), 'visa_routes', ['passport_nationality'], unique=False)
    op.create_index(op.f('ix_visa_routes_research_status'), 'visa_routes', ['research_status'], unique=False)
    op.create_index(op.f('ix_visa_routes_route_key'), 'visa_routes', ['route_key'], unique=True)
    op.create_index(op.f('ix_visa_routes_snapshot_date'), 'visa_routes', ['snapshot_date'], unique=False)
    op.create_table('visa_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('update_mode', sa.String(length=16), nullable=False),
    sa.Column('automatic_refresh_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('git_commit', sa.String(length=64), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visa_snapshots_snapshot_date'), 'visa_snapshots', ['snapshot_date'], unique=True)
    op.create_table('adapter_development_tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('route_key', sa.String(length=400), nullable=False),
    sa.Column('route_id', sa.String(length=32), nullable=True),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('portal_evidence', sa.JSON(), nullable=False),
    sa.Column('fee_evidence', sa.JSON(), nullable=False),
    sa.Column('jurisdiction_evidence', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['visa_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adapter_development_tasks_org_id'), 'adapter_development_tasks', ['org_id'], unique=False)
    op.create_index(op.f('ix_adapter_development_tasks_route_key'), 'adapter_development_tasks', ['route_key'], unique=False)
    op.create_index(op.f('ix_adapter_development_tasks_status'), 'adapter_development_tasks', ['status'], unique=False)
    op.create_table('document_requirement_sets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('route_id', sa.String(length=32), nullable=True),
    sa.Column('policy_id', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('required_documents', sa.JSON(), nullable=False),
    sa.Column('conditional_documents', sa.JSON(), nullable=False),
    sa.Column('financial_evidence', sa.Text(), nullable=False),
    sa.Column('research_status', sa.String(length=32), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['visa_policies.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['visa_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_requirement_sets_policy_id'), 'document_requirement_sets', ['policy_id'], unique=False)
    op.create_index(op.f('ix_document_requirement_sets_route_id'), 'document_requirement_sets', ['route_id'], unique=False)
    op.create_index(op.f('ix_document_requirement_sets_snapshot_date'), 'document_requirement_sets', ['snapshot_date'], unique=False)
    op.create_table('policy_applicability_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('policy_id', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('condition_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['visa_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_applicability_rules_policy_id'), 'policy_applicability_rules', ['policy_id'], unique=False)
    op.create_table('route_matrix_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('matrix_key', sa.String(length=400), nullable=False),
    sa.Column('passport_nationality', sa.String(length=3), nullable=False),
    sa.Column('passport_issuing_country', sa.String(length=8), nullable=False),
    sa.Column('travel_document_type', sa.String(length=48), nullable=False),
    sa.Column('lawful_country_of_residence', sa.String(length=8), nullable=False),
    sa.Column('destination_country', sa.String(length=3), nullable=False),
    sa.Column('visa_category', sa.String(length=48), nullable=False),
    sa.Column('visa_subtype', sa.String(length=48), nullable=False),
    sa.Column('disposition', sa.String(length=48), nullable=False),
    sa.Column('route_id', sa.String(length=32), nullable=True),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['visa_routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matrix_key', name='uq_matrix_key')
    )
    op.create_index(op.f('ix_route_matrix_entries_destination_country'), 'route_matrix_entries', ['destination_country'], unique=False)
    op.create_index(op.f('ix_route_matrix_entries_disposition'), 'route_matrix_entries', ['disposition'], unique=False)
    op.create_index(op.f('ix_route_matrix_entries_matrix_key'), 'route_matrix_entries', ['matrix_key'], unique=False)
    op.create_index(op.f('ix_route_matrix_entries_passport_nationality'), 'route_matrix_entries', ['passport_nationality'], unique=False)
    op.create_index(op.f('ix_route_matrix_entries_route_id'), 'route_matrix_entries', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_matrix_entries_snapshot_date'), 'route_matrix_entries', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_route_matrix_entries_travel_document_type'), 'route_matrix_entries', ['travel_document_type'], unique=False)
    op.create_index(op.f('ix_route_matrix_entries_visa_category'), 'route_matrix_entries', ['visa_category'], unique=False)
    op.create_table('route_resolutions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('raw_input', sa.JSON(), nullable=False),
    sa.Column('normalized_input', sa.JSON(), nullable=False),
    sa.Column('route_key', sa.String(length=400), nullable=False),
    sa.Column('route_id', sa.String(length=32), nullable=True),
    sa.Column('route_version', sa.Integer(), nullable=True),
    sa.Column('readiness_status', sa.String(length=48), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['visa_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_resolutions_case_id'), 'route_resolutions', ['case_id'], unique=False)
    op.create_index(op.f('ix_route_resolutions_org_id'), 'route_resolutions', ['org_id'], unique=False)
    op.create_index(op.f('ix_route_resolutions_route_key'), 'route_resolutions', ['route_key'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('evidence_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('retrieved_at', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['source_evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_snapshots_content_hash'), 'source_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_snapshots_evidence_id'), 'source_snapshots', ['evidence_id'], unique=False)
    op.create_table('visa_policy_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('policy_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['visa_policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'version', name='uq_policy_version')
    )
    op.create_index(op.f('ix_visa_policy_versions_content_hash'), 'visa_policy_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_visa_policy_versions_policy_id'), 'visa_policy_versions', ['policy_id'], unique=False)
    op.create_table('visa_route_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('route_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['visa_routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'version', name='uq_route_version')
    )
    op.create_index(op.f('ix_visa_route_versions_content_hash'), 'visa_route_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_visa_route_versions_route_id'), 'visa_route_versions', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visa_route_versions_route_id'), table_name='visa_route_versions')
    op.drop_index(op.f('ix_visa_route_versions_content_hash'), table_name='visa_route_versions')
    op.drop_table('visa_route_versions')
    op.drop_index(op.f('ix_visa_policy_versions_policy_id'), table_name='visa_policy_versions')
    op.drop_index(op.f('ix_visa_policy_versions_content_hash'), table_name='visa_policy_versions')
    op.drop_table('visa_policy_versions')
    op.drop_index(op.f('ix_source_snapshots_evidence_id'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_content_hash'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_route_resolutions_route_key'), table_name='route_resolutions')
    op.drop_index(op.f('ix_route_resolutions_org_id'), table_name='route_resolutions')
    op.drop_index(op.f('ix_route_resolutions_case_id'), table_name='route_resolutions')
    op.drop_table('route_resolutions')
    op.drop_index(op.f('ix_route_matrix_entries_visa_category'), table_name='route_matrix_entries')
    op.drop_index(op.f('ix_route_matrix_entries_travel_document_type'), table_name='route_matrix_entries')
    op.drop_index(op.f('ix_route_matrix_entries_snapshot_date'), table_name='route_matrix_entries')
    op.drop_index(op.f('ix_route_matrix_entries_route_id'), table_name='route_matrix_entries')
    op.drop_index(op.f('ix_route_matrix_entries_passport_nationality'), table_name='route_matrix_entries')
    op.drop_index(op.f('ix_route_matrix_entries_matrix_key'), table_name='route_matrix_entries')
    op.drop_index(op.f('ix_route_matrix_entries_disposition'), table_name='route_matrix_entries')
    op.drop_index(op.f('ix_route_matrix_entries_destination_country'), table_name='route_matrix_entries')
    op.drop_table('route_matrix_entries')
    op.drop_index(op.f('ix_policy_applicability_rules_policy_id'), table_name='policy_applicability_rules')
    op.drop_table('policy_applicability_rules')
    op.drop_index(op.f('ix_document_requirement_sets_snapshot_date'), table_name='document_requirement_sets')
    op.drop_index(op.f('ix_document_requirement_sets_route_id'), table_name='document_requirement_sets')
    op.drop_index(op.f('ix_document_requirement_sets_policy_id'), table_name='document_requirement_sets')
    op.drop_table('document_requirement_sets')
    op.drop_index(op.f('ix_adapter_development_tasks_status'), table_name='adapter_development_tasks')
    op.drop_index(op.f('ix_adapter_development_tasks_route_key'), table_name='adapter_development_tasks')
    op.drop_index(op.f('ix_adapter_development_tasks_org_id'), table_name='adapter_development_tasks')
    op.drop_table('adapter_development_tasks')
    op.drop_index(op.f('ix_visa_snapshots_snapshot_date'), table_name='visa_snapshots')
    op.drop_table('visa_snapshots')
    op.drop_index(op.f('ix_visa_routes_snapshot_date'), table_name='visa_routes')
    op.drop_index(op.f('ix_visa_routes_route_key'), table_name='visa_routes')
    op.drop_index(op.f('ix_visa_routes_research_status'), table_name='visa_routes')
    op.drop_index(op.f('ix_visa_routes_passport_nationality'), table_name='visa_routes')
    op.drop_index(op.f('ix_visa_routes_passport_issuing_country'), table_name='visa_routes')
    op.drop_index(op.f('ix_visa_routes_lawful_country_of_residence'), table_name='visa_routes')
    op.drop_index(op.f('ix_visa_routes_disposition'), table_name='visa_routes')
    op.drop_index(op.f('ix_visa_routes_destination_country'), table_name='visa_routes')
    op.drop_table('visa_routes')
    op.drop_index(op.f('ix_visa_policies_snapshot_date'), table_name='visa_policies')
    op.drop_index(op.f('ix_visa_policies_policy_uid'), table_name='visa_policies')
    op.drop_index(op.f('ix_visa_policies_destination_country'), table_name='visa_policies')
    op.drop_table('visa_policies')
    op.drop_index(op.f('ix_visa_fee_versions_snapshot_date'), table_name='visa_fee_versions')
    op.drop_index(op.f('ix_visa_fee_versions_fee_uid'), table_name='visa_fee_versions')
    op.drop_index(op.f('ix_visa_fee_versions_destination_country'), table_name='visa_fee_versions')
    op.drop_index(op.f('ix_visa_fee_versions_content_hash'), table_name='visa_fee_versions')
    op.drop_table('visa_fee_versions')
    op.drop_index(op.f('ix_source_evidence_source_authority'), table_name='source_evidence')
    op.drop_index(op.f('ix_source_evidence_snapshot_date'), table_name='source_evidence')
    op.drop_index(op.f('ix_source_evidence_final_hostname'), table_name='source_evidence')
    op.drop_index(op.f('ix_source_evidence_content_hash'), table_name='source_evidence')
    op.drop_table('source_evidence')
    op.drop_index(op.f('ix_snapshot_research_batches_stage'), table_name='snapshot_research_batches')
    op.drop_index(op.f('ix_snapshot_research_batches_snapshot_date'), table_name='snapshot_research_batches')
    op.drop_index(op.f('ix_snapshot_research_batches_destination_country'), table_name='snapshot_research_batches')
    op.drop_index(op.f('ix_snapshot_research_batches_batch_key'), table_name='snapshot_research_batches')
    op.drop_table('snapshot_research_batches')
    op.drop_index(op.f('ix_snapshot_passport_validity_rules_snapshot_date'), table_name='snapshot_passport_validity_rules')
    op.drop_index(op.f('ix_snapshot_passport_validity_rules_destination_country'), table_name='snapshot_passport_validity_rules')
    op.drop_table('snapshot_passport_validity_rules')
    op.drop_index(op.f('ix_snapshot_conflicts_snapshot_date'), table_name='snapshot_conflicts')
    op.drop_index(op.f('ix_snapshot_conflicts_route_key'), table_name='snapshot_conflicts')
    op.drop_index(op.f('ix_snapshot_conflicts_destination_country'), table_name='snapshot_conflicts')
    op.drop_table('snapshot_conflicts')
    op.drop_index(op.f('ix_route_readiness_evaluations_route_key'), table_name='route_readiness_evaluations')
    op.drop_index(op.f('ix_route_readiness_evaluations_org_id'), table_name='route_readiness_evaluations')
    op.drop_table('route_readiness_evaluations')
    op.drop_index(op.f('ix_official_portals_snapshot_date'), table_name='official_portals')
    op.drop_index(op.f('ix_official_portals_portal_uid'), table_name='official_portals')
    op.drop_index(op.f('ix_official_portals_destination_country'), table_name='official_portals')
    op.drop_table('official_portals')
    op.drop_index(op.f('ix_human_review_tasks_status'), table_name='human_review_tasks')
    op.drop_index(op.f('ix_human_review_tasks_snapshot_date'), table_name='human_review_tasks')
    op.drop_index(op.f('ix_human_review_tasks_org_id'), table_name='human_review_tasks')
    op.drop_index(op.f('ix_human_review_tasks_kind'), table_name='human_review_tasks')
    op.drop_table('human_review_tasks')
    op.drop_index(op.f('ix_consular_jurisdiction_rules_snapshot_date'), table_name='consular_jurisdiction_rules')
    op.drop_index(op.f('ix_consular_jurisdiction_rules_residence_jurisdiction'), table_name='consular_jurisdiction_rules')
    op.drop_index(op.f('ix_consular_jurisdiction_rules_destination_country'), table_name='consular_jurisdiction_rules')
    op.drop_table('consular_jurisdiction_rules')
    op.drop_index(op.f('ix_authorized_visa_centers_snapshot_date'), table_name='authorized_visa_centers')
    op.drop_index(op.f('ix_authorized_visa_centers_destination_country'), table_name='authorized_visa_centers')
    op.drop_table('authorized_visa_centers')
    # ### end Alembic commands ###
